<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Unity/Packages/com.abilitykit.demo.tiny.turn/Runtime/Logic/*.cs" />
  </ItemGroup>
</Project>
