using AbilityKit.Demo.Moba.Config.BattleDemo.MO;
using AbilityKit.Demo.Moba.Config.Core;
using AbilityKit.Demo.Moba.Share.Config;

[assembly: MobaConfigTable(MobaConfigPaths.CharactersFile, typeof(CharacterDTO), typeof(CharacterMO), ConfigGroupNames.LegacyJson, 0)]
[assembly: MobaConfigTable(MobaConfigPaths.AttributeTemplatesFile, typeof(BattleAttributeTemplateDTO), typeof(BattleAttributeTemplateMO), ConfigGroupNames.LegacyJson, 10)]
[assembly: MobaConfigTable(MobaConfigPaths.AttributeTypesFile, typeof(AttrTypeDTO), typeof(AttrTypeMO), ConfigGroupNames.LegacyJson, 20)]
[assembly: MobaConfigTable(MobaConfigPaths.SkillsFile, typeof(SkillDTO), typeof(SkillMO), ConfigGroupNames.LegacyJson, 30)]
[assembly: MobaConfigTable(MobaConfigPaths.PassiveSkillsFile, typeof(PassiveSkillDTO), typeof(PassiveSkillMO), ConfigGroupNames.LegacyJson, 40)]
[assembly: MobaConfigTable(MobaConfigPaths.SkillFlowsFile, typeof(SkillFlowDTO), typeof(SkillFlowMO), ConfigGroupNames.LegacyJson, 50)]
[assembly: MobaConfigTable(MobaConfigPaths.SkillLevelTablesFile, typeof(SkillLevelTableDTO), typeof(SkillLevelTableMO), ConfigGroupNames.LegacyJson, 60)]
[assembly: MobaConfigTable(MobaConfigPaths.ModelsFile, typeof(ModelDTO), typeof(ModelMO), ConfigGroupNames.LegacyJson, 70)]
[assembly: MobaConfigTable(MobaConfigPaths.BuffsFile, typeof(BuffDTO), typeof(BuffMO), ConfigGroupNames.LegacyJson, 80)]
[assembly: MobaConfigTable(MobaConfigPaths.ContinuousProcessesFile, typeof(ContinuousProcessDTO), typeof(ContinuousProcessMO), ConfigGroupNames.LegacyJson, 90)]
[assembly: MobaConfigTable(MobaConfigPaths.ProjectileLaunchersFile, typeof(ProjectileLauncherDTO), typeof(ProjectileLauncherMO), ConfigGroupNames.LegacyJson, 100)]
[assembly: MobaConfigTable(MobaConfigPaths.ProjectilesFile, typeof(ProjectileDTO), typeof(ProjectileMO), ConfigGroupNames.LegacyJson, 110)]
[assembly: MobaConfigTable(MobaConfigPaths.AoesFile, typeof(AoeDTO), typeof(AoeMO), ConfigGroupNames.LegacyJson, 120)]
[assembly: MobaConfigTable(MobaConfigPaths.EmittersFile, typeof(EmitterDTO), typeof(EmitterMO), ConfigGroupNames.LegacyJson, 130)]
[assembly: MobaConfigTable(MobaConfigPaths.SummonsFile, typeof(SummonDTO), typeof(SummonMO), ConfigGroupNames.LegacyJson, 140)]
[assembly: MobaConfigTable(MobaConfigPaths.SummonAttrInheritsFile, typeof(SummonAttrInheritDTO), typeof(SummonAttrInheritMO), ConfigGroupNames.LegacyJson, 150)]
[assembly: MobaConfigTable(MobaConfigPaths.ComponentTemplatesFile, typeof(ComponentTemplateDTO), typeof(ComponentTemplateMO), ConfigGroupNames.LegacyJson, 160)]
[assembly: MobaConfigTable(MobaConfigPaths.SkillButtonTemplatesFile, typeof(SkillButtonTemplateDTO), typeof(SkillButtonTemplateMO), ConfigGroupNames.LegacyJson, 170)]
[assembly: MobaConfigTable(MobaConfigPaths.TagTemplatesFile, typeof(TagTemplateDTO), typeof(TagTemplateMO), ConfigGroupNames.LegacyJson, 180)]
[assembly: MobaConfigTable(MobaConfigPaths.ContinuousTagTemplatesFile, typeof(ContinuousTagTemplateDTO), typeof(ContinuousTagTemplateMO), ConfigGroupNames.LegacyJson, 190)]
[assembly: MobaConfigTable(MobaConfigPaths.SearchQueryTemplatesFile, typeof(SearchQueryTemplateDTO), typeof(SearchQueryTemplateMO), ConfigGroupNames.LegacyJson, 200)]
[assembly: MobaConfigTable(MobaConfigPaths.SpawnSummonActionTemplatesFile, typeof(SpawnSummonActionTemplateDTO), typeof(SpawnSummonActionTemplateMO), ConfigGroupNames.LegacyJson, 210)]
[assembly: MobaConfigTable(MobaConfigPaths.PresentationTemplatesFile, typeof(PresentationTemplateDTO), typeof(PresentationTemplateMO), ConfigGroupNames.LegacyJson, 220)]
[assembly: MobaConfigTable(MobaConfigPaths.BattleMapsFile, typeof(BattleMapDTO), typeof(BattleMapMO), ConfigGroupNames.LegacyJson, 230)]
[assembly: MobaConfigTable(MobaConfigPaths.GameplaysFile, typeof(GameplayDTO), typeof(GameplayMO), ConfigGroupNames.LegacyJson, 240)]
[assembly: MobaConfigTable(MobaConfigPaths.MotionGroupsFile, typeof(MotionGroupDTO), typeof(MotionGroupMO), ConfigGroupNames.LegacyJson, 250)]
