<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AbilityKit.HotReload">
      <HintPath>..\..\Library\ScriptAssemblies\AbilityKit.HotReload.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="AbilityKit.World.DI">
      <HintPath>..\..\Library\ScriptAssemblies\AbilityKit.World.DI.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Entitas">
      <HintPath>..\..\Packages\com.abilitykit.thirdparty.entitas\Entitas\Entitas.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
