#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using AbilityKit.Ability.Triggering.Runtime;
using AbilityKit.Triggering.CodeGen;
using AbilityKit.Triggering.Eventing;
using UnityEditor;
using UnityEngine;

namespace AbilityKit.Ability.Editor.Utilities
{
    internal static class TriggerPlanCompilerCodegenMenu
    {
        private const string OutputPath = "Packages/com.abilitykit.ability.editor/Editor/Ability/Editor/Triggering/Generated/GeneratedTriggerPlanCompiler.g.cs";

        [MenuItem("Tools/AbilityKit/Framework/Triggering/Codegen/Generate Plan Compiler")]
        public static void Generate()
        {
            var actions = FindActions();
            var conditions = FindConditions();

            var code = Emit(actions, conditions);
            var full = Path.GetFullPath(OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(full));
            File.WriteAllText(full, code);

            AssetDatabase.Refresh();
            Debug.Log($"[TriggerPlanCompilerCodegen] Generated: {full}\nActions={actions.Count}, Conditions={conditions.Count}");
        }

        private sealed class ActionItem
        {
            public string Name;
            public int Id;
            public TriggerParamAttribute[] Params;
        }

        private sealed class ConditionItem
        {
            public string Type;
            public TriggerParamAttribute[] Params;
        }

        private static List<ActionItem> FindActions()
        {
            var list = new List<ActionItem>();

            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] types;
                try { types = asm.GetTypes(); }
                catch (ReflectionTypeLoadException ex) { types = ex.Types; }
                if (types == null) continue;

                foreach (var t in types)
                {
                    if (t == null) continue;

                    var classAttr = t.GetCustomAttribute<TriggerActionAttribute>(false);
                    if (classAttr != null && !string.IsNullOrEmpty(classAttr.Name))
                    {
                        list.Add(new ActionItem
                        {
                            Name = classAttr.Name,
                            Id = StableStringId.Get("action:" + classAttr.Name),
                            Params = t.GetCustomAttributes<TriggerParamAttribute>(false).ToArray()
                        });
                    }

                    var methods = t.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
                    foreach (var m in methods)
                    {
                        var attr = m.GetCustomAttribute<TriggerActionAttribute>(false);
                        if (attr == null || string.IsNullOrEmpty(attr.Name)) continue;
                        list.Add(new ActionItem
                        {
                            Name = attr.Name,
                            Id = StableStringId.Get("action:" + attr.Name),
                            Params = m.GetCustomAttributes<TriggerParamAttribute>(false).ToArray()
                        });
                    }
                }
            }

            return list
                .GroupBy(x => x.Id)
                .Select(g => g.First())
                .OrderBy(x => x.Id)
                .ToList();
        }

        private static List<ConditionItem> FindConditions()
        {
            var list = new List<ConditionItem>();

            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] types;
                try { types = asm.GetTypes(); }
                catch (ReflectionTypeLoadException ex) { types = ex.Types; }
                if (types == null) continue;

                foreach (var t in types)
                {
                    if (t == null) continue;
                    var attr = t.GetCustomAttribute<TriggerConditionAttribute>(false);
                    if (attr == null || string.IsNullOrEmpty(attr.Type)) continue;

                    list.Add(new ConditionItem
                    {
                        Type = attr.Type,
                        Params = t.GetCustomAttributes<TriggerParamAttribute>(false).ToArray()
                    });
                }
            }

            return list
                .GroupBy(x => x.Type, StringComparer.Ordinal)
                .Select(g => g.First())
                .OrderBy(x => x.Type, StringComparer.Ordinal)
                .ToList();
        }

        private static string Emit(List<ActionItem> actions, List<ConditionItem> conditions)
        {
            var nl = "\n";
            var code = "";
            code += "// <auto-generated />" + nl;
            code += "#if UNITY_EDITOR" + nl;
            code += "using System;" + nl;
            code += "using System.Collections.Generic;" + nl;
            code += "using AbilityKit.Ability.Triggering.Runtime;" + nl;
            code += "using AbilityKit.Triggering.Runtime.Plan;" + nl;
            code += "using AbilityKit.Triggering.Registry;" + nl;
            code += nl;
            code += "namespace AbilityKit.Ability.Editor.Utilities" + nl;
            code += "{" + nl;
            code += "    internal static partial class GeneratedTriggerPlanCompiler" + nl;
            code += "    {" + nl;

            code += "        public static bool TryCompileAction(ActionId id, Dictionary<string, object> args, Func<string, int> payloadFieldIdResolver, out ActionCallPlan[] plans)" + nl;
            code += "        {" + nl;
            code += "            plans = null;" + nl;
            code += "            switch (id.Value)" + nl;
            code += "            {" + nl;

            foreach (var a in actions)
            {
                code += $"                case {a.Id}:" + nl;
                code += "                {" + nl;

                var ps = a.Params?.OrderBy(p => p.Index).ToArray() ?? Array.Empty<TriggerParamAttribute>();
                if (ps.Length == 0)
                {
                    code += "                    plans = new[] { new ActionCallPlan(id) };" + nl;
                    code += "                    return true;" + nl;
                    code += "                }" + nl;
                    continue;
                }

                if (ps.Length > 2 || ps.Any(p => p.Type != ETriggerParamType.Int))
                {
                    code += "                    return false;" + nl;
                    code += "                }" + nl;
                    continue;
                }

                code += $"                    var a0 = TryReadSchemaNumericValueRef(args, \"{ps[0].Name}\", payloadFieldIdResolver);" + nl;
                if (ps.Length == 2)
                {
                    code += $"                    var a1 = TryReadSchemaNumericValueRef(args, \"{ps[1].Name}\", payloadFieldIdResolver);" + nl;
                    code += "                    if (a0.HasValue && a1.HasValue) plans = new[] { new ActionCallPlan(id, a0.Value, a1.Value) };" + nl;
                    code += "                    else if (a0.HasValue) plans = new[] { new ActionCallPlan(id, a0.Value) };" + nl;
                    code += "                    else plans = new[] { new ActionCallPlan(id) };" + nl;
                }
                else
                {
                    code += "                    if (a0.HasValue) plans = new[] { new ActionCallPlan(id, a0.Value) };" + nl;
                    code += "                    else plans = new[] { new ActionCallPlan(id) };" + nl;
                }

                code += "                    return true;" + nl;
                code += "                }" + nl;
            }

            code += "                default: return false;" + nl;
            code += "            }" + nl;
            code += "        }" + nl;

            code += nl;
            code += "        public static bool TryCompileCondition(string type, Dictionary<string, object> args, Func<string, int> payloadFieldIdResolver, out PredicateExprPlan plan)" + nl;
            code += "        {" + nl;
            code += "            plan = default;" + nl;
            code += "            if (type == null) return false;" + nl;

            foreach (var c in conditions)
            {
                // 目前只为 arg_eq / arg_gt 生成代码（整数比较）。
                if (!string.Equals(c.Type, TriggerConditionTypes.ArgEq, StringComparison.Ordinal) &&
                    !string.Equals(c.Type, TriggerConditionTypes.ArgGt, StringComparison.Ordinal))
                {
                    continue;
                }

                var ps = c.Params?.OrderBy(p => p.Index).ToArray() ?? Array.Empty<TriggerParamAttribute>();
                var leftName = ps.Length > 0 ? ps[0].Name : "key";
                var rightName = ps.Length > 1 ? ps[1].Name : "value";
                var op = string.Equals(c.Type, TriggerConditionTypes.ArgEq, StringComparison.Ordinal) ? "ECompareOp.Equal" : "ECompareOp.GreaterThan";

                code += $"            if (string.Equals(type, \"{c.Type}\", StringComparison.Ordinal))" + nl;
                code += "            {" + nl;
                code += $"                var left = TryReadSchemaNumericValueRef(args, \"{leftName}\", payloadFieldIdResolver);" + nl;
                code += $"                var right = TryReadSchemaNumericValueRef(args, \"{rightName}\", payloadFieldIdResolver);" + nl;
                code += "                if (!left.HasValue || !right.HasValue) return false;" + nl;
                code += $"                plan = new PredicateExprPlan(new[] {{ BoolExprNode.Compare({op}, left.Value, right.Value) }});" + nl;
                code += "                return true;" + nl;
                code += "            }" + nl;
            }

            code += "            return false;" + nl;
            code += "        }" + nl;

            code += nl;
            code += "        private static NumericValueRef? TryReadSchemaNumericValueRef(Dictionary<string, object> args, string name, Func<string, int> payloadFieldIdResolver)" + nl;
            code += "        {" + nl;
            code += "            if (args == null || string.IsNullOrEmpty(name)) return null;" + nl;
            code += "            if (args.TryGetValue(name + \"_field\", out var fObj) && fObj is string f && !string.IsNullOrEmpty(f))" + nl;
            code += "            {" + nl;
            code += "                return NumericValueRef.PayloadField(ResolveFieldId(payloadFieldIdResolver, f));" + nl;
            code += "            }" + nl;
            code += "            if (args.TryGetValue(name + \"_const\", out var cObj) && cObj != null)" + nl;
            code += "            {" + nl;
            code += "                return NumericValueRef.Const(Convert.ToDouble(cObj));" + nl;
            code += "            }" + nl;
            code += "            if (args.TryGetValue(name, out var vObj) && vObj != null)" + nl;
            code += "            {" + nl;
            code += "                if (vObj is string s && !string.IsNullOrEmpty(s)) return NumericValueRef.PayloadField(ResolveFieldId(payloadFieldIdResolver, s));" + nl;
            code += "                return NumericValueRef.Const(Convert.ToDouble(vObj));" + nl;
            code += "            }" + nl;
            code += "            return null;" + nl;
            code += "        }" + nl;

            code += nl;
            code += "        private static int ResolveFieldId(Func<string, int> payloadFieldIdResolver, string fieldName)" + nl;
            code += "        {" + nl;
            code += "            if (payloadFieldIdResolver == null) throw new InvalidOperationException(\"payloadFieldIdResolver is null\");" + nl;
            code += "            var id = payloadFieldIdResolver(fieldName);" + nl;
            code += "            if (id == 0) throw new InvalidOperationException($\"FieldId resolve failed for '{fieldName}'\");" + nl;
            code += "            return id;" + nl;
            code += "        }" + nl;

            code += "    }" + nl;
            code += "}" + nl;
            code += "#endif" + nl;
            return code;
        }
    }
}
#endif
