
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class AbilityNodes
{
    private readonly System.Collections.Generic.Dictionary<int, DRAbilityNodes> _dataMap;
    private readonly System.Collections.Generic.List<DRAbilityNodes> _dataList;
    
    public AbilityNodes(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRAbilityNodes>(n);
        _dataList = new System.Collections.Generic.List<DRAbilityNodes>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRAbilityNodes _v;
            _v = global::moba_luban.DRAbilityNodes.DeserializeDRAbilityNodes(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRAbilityNodes> DataMap => _dataMap;
    public System.Collections.Generic.List<DRAbilityNodes> DataList => _dataList;

    public DRAbilityNodes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRAbilityNodes Get(int key) => _dataMap[key];
    public DRAbilityNodes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

