
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class Aoes
{
    private readonly System.Collections.Generic.Dictionary<int, DRAoes> _dataMap;
    private readonly System.Collections.Generic.List<DRAoes> _dataList;
    
    public Aoes(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRAoes>(n);
        _dataList = new System.Collections.Generic.List<DRAoes>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRAoes _v;
            _v = global::moba_luban.DRAoes.DeserializeDRAoes(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRAoes> DataMap => _dataMap;
    public System.Collections.Generic.List<DRAoes> DataList => _dataList;

    public DRAoes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRAoes Get(int key) => _dataMap[key];
    public DRAoes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

