
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class AttributeTemplates
{
    private readonly System.Collections.Generic.Dictionary<int, DRAttributeTemplates> _dataMap;
    private readonly System.Collections.Generic.List<DRAttributeTemplates> _dataList;
    
    public AttributeTemplates(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRAttributeTemplates>(n);
        _dataList = new System.Collections.Generic.List<DRAttributeTemplates>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRAttributeTemplates _v;
            _v = global::moba_luban.DRAttributeTemplates.DeserializeDRAttributeTemplates(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRAttributeTemplates> DataMap => _dataMap;
    public System.Collections.Generic.List<DRAttributeTemplates> DataList => _dataList;

    public DRAttributeTemplates GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRAttributeTemplates Get(int key) => _dataMap[key];
    public DRAttributeTemplates this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

