
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class AttrTypes
{
    private readonly System.Collections.Generic.Dictionary<int, DRAttrTypes> _dataMap;
    private readonly System.Collections.Generic.List<DRAttrTypes> _dataList;
    
    public AttrTypes(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRAttrTypes>(n);
        _dataList = new System.Collections.Generic.List<DRAttrTypes>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRAttrTypes _v;
            _v = global::moba_luban.DRAttrTypes.DeserializeDRAttrTypes(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRAttrTypes> DataMap => _dataMap;
    public System.Collections.Generic.List<DRAttrTypes> DataList => _dataList;

    public DRAttrTypes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRAttrTypes Get(int key) => _dataMap[key];
    public DRAttrTypes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

