
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class BattleMaps
{
    private readonly System.Collections.Generic.Dictionary<int, DRBattleMaps> _dataMap;
    private readonly System.Collections.Generic.List<DRBattleMaps> _dataList;
    
    public BattleMaps(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRBattleMaps>(n);
        _dataList = new System.Collections.Generic.List<DRBattleMaps>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRBattleMaps _v;
            _v = global::moba_luban.DRBattleMaps.DeserializeDRBattleMaps(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRBattleMaps> DataMap => _dataMap;
    public System.Collections.Generic.List<DRBattleMaps> DataList => _dataList;

    public DRBattleMaps GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRBattleMaps Get(int key) => _dataMap[key];
    public DRBattleMaps this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

