
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class Brains
{
    private readonly System.Collections.Generic.Dictionary<int, DRBrains> _dataMap;
    private readonly System.Collections.Generic.List<DRBrains> _dataList;
    
    public Brains(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRBrains>(n);
        _dataList = new System.Collections.Generic.List<DRBrains>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRBrains _v;
            _v = global::moba_luban.DRBrains.DeserializeDRBrains(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.BrainId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRBrains> DataMap => _dataMap;
    public System.Collections.Generic.List<DRBrains> DataList => _dataList;

    public DRBrains GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRBrains Get(int key) => _dataMap[key];
    public DRBrains this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

