
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class ComponentTemplates
{
    private readonly System.Collections.Generic.Dictionary<int, DRComponentTemplates> _dataMap;
    private readonly System.Collections.Generic.List<DRComponentTemplates> _dataList;
    
    public ComponentTemplates(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRComponentTemplates>(n);
        _dataList = new System.Collections.Generic.List<DRComponentTemplates>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRComponentTemplates _v;
            _v = global::moba_luban.DRComponentTemplates.DeserializeDRComponentTemplates(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRComponentTemplates> DataMap => _dataMap;
    public System.Collections.Generic.List<DRComponentTemplates> DataList => _dataList;

    public DRComponentTemplates GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRComponentTemplates Get(int key) => _dataMap[key];
    public DRComponentTemplates this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

