
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class ContinuousTagTemplates
{
    private readonly System.Collections.Generic.Dictionary<int, DRContinuousTagTemplates> _dataMap;
    private readonly System.Collections.Generic.List<DRContinuousTagTemplates> _dataList;
    
    public ContinuousTagTemplates(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRContinuousTagTemplates>(n);
        _dataList = new System.Collections.Generic.List<DRContinuousTagTemplates>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRContinuousTagTemplates _v;
            _v = global::moba_luban.DRContinuousTagTemplates.DeserializeDRContinuousTagTemplates(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRContinuousTagTemplates> DataMap => _dataMap;
    public System.Collections.Generic.List<DRContinuousTagTemplates> DataList => _dataList;

    public DRContinuousTagTemplates GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRContinuousTagTemplates Get(int key) => _dataMap[key];
    public DRContinuousTagTemplates this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

