
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRAbilityNodes : Luban.BeanBase
{
    public DRAbilityNodes(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Kind = _buf.ReadString();
        Path = _buf.ReadString();
        Pointer = _buf.ReadString();
        ValueJson = _buf.ReadString();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRAbilityNodes DeserializeDRAbilityNodes(ByteBuf _buf)
    {
        return new DRAbilityNodes(_buf);
    }

    /// <summary>
    /// Ability JSON tree nodes; Pointer uses RFC 6901.
    /// </summary>
    public readonly int Id;
    public readonly string Kind;
    public readonly string Path;
    public readonly string Pointer;
    public readonly string ValueJson;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 2117013333;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Kind:" + Kind + ","
        + "Path:" + Path + ","
        + "Pointer:" + Pointer + ","
        + "ValueJson:" + ValueJson + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

