
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRAoes : Luban.BeanBase
{
    public DRAoes(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AttachMode = _buf.ReadInt();
        CollisionLayerMask = _buf.ReadInt();
        DelayMs = _buf.ReadInt();
        DurationMs = _buf.ReadInt();
        IntervalMs = _buf.ReadInt();
        MaxTargets = _buf.ReadInt();
        ModelId = _buf.ReadInt();
        Name = _buf.ReadString();
        OffsetX = _buf.ReadInt();
        OffsetY = _buf.ReadInt();
        OffsetZ = _buf.ReadFloat();
        {int n0 = _buf.ReadSize(); OnDelayTriggerIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnDelayTriggerIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OnEnterTriggerIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnEnterTriggerIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OnIntervalTriggerIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnIntervalTriggerIds.Add(_e0);}}
        Radius = _buf.ReadFloat();
        VfxId = _buf.ReadInt();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRAoes DeserializeDRAoes(ByteBuf _buf)
    {
        return new DRAoes(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly int AttachMode;
    public readonly int CollisionLayerMask;
    public readonly int DelayMs;
    public readonly int DurationMs;
    public readonly int IntervalMs;
    public readonly int MaxTargets;
    public readonly int ModelId;
    public readonly string Name;
    public readonly int OffsetX;
    public readonly int OffsetY;
    public readonly float OffsetZ;
    public readonly System.Collections.Generic.List<int> OnDelayTriggerIds;
    public readonly System.Collections.Generic.List<int> OnEnterTriggerIds;
    public readonly System.Collections.Generic.List<int> OnIntervalTriggerIds;
    public readonly float Radius;
    public readonly int VfxId;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 2024557322;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AttachMode:" + AttachMode + ","
        + "CollisionLayerMask:" + CollisionLayerMask + ","
        + "DelayMs:" + DelayMs + ","
        + "DurationMs:" + DurationMs + ","
        + "IntervalMs:" + IntervalMs + ","
        + "MaxTargets:" + MaxTargets + ","
        + "ModelId:" + ModelId + ","
        + "Name:" + Name + ","
        + "OffsetX:" + OffsetX + ","
        + "OffsetY:" + OffsetY + ","
        + "OffsetZ:" + OffsetZ + ","
        + "OnDelayTriggerIds:" + Luban.StringUtil.CollectionToString(OnDelayTriggerIds) + ","
        + "OnEnterTriggerIds:" + Luban.StringUtil.CollectionToString(OnEnterTriggerIds) + ","
        + "OnIntervalTriggerIds:" + Luban.StringUtil.CollectionToString(OnIntervalTriggerIds) + ","
        + "Radius:" + Radius + ","
        + "VfxId:" + VfxId + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

