
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRBattleMaps : Luban.BeanBase
{
    public DRBattleMaps(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Bounds = _buf.ReadString();
        CollisionObjects = _buf.ReadString();
        Name = _buf.ReadString();
        SpawnPoints = _buf.ReadString();
        WalkableAreas = _buf.ReadString();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRBattleMaps DeserializeDRBattleMaps(ByteBuf _buf)
    {
        return new DRBattleMaps(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly string Bounds;
    public readonly string CollisionObjects;
    public readonly string Name;
    public readonly string SpawnPoints;
    public readonly string WalkableAreas;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -1381451107;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Bounds:" + Bounds + ","
        + "CollisionObjects:" + CollisionObjects + ","
        + "Name:" + Name + ","
        + "SpawnPoints:" + SpawnPoints + ","
        + "WalkableAreas:" + WalkableAreas + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

