
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRBrains : Luban.BeanBase
{
    public DRBrains(ByteBuf _buf) 
    {
        BrainId = _buf.ReadInt();
        DecisionName = _buf.ReadString();
        DriverKind = _buf.ReadString();
        SkillSelectionPolicy = _buf.ReadString();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRBrains DeserializeDRBrains(ByteBuf _buf)
    {
        return new DRBrains(_buf);
    }

    /// <summary>
    /// Promoted from resource_documents.xlsx; edit this table as the source.
    /// </summary>
    public readonly int BrainId;
    public readonly string DecisionName;
    public readonly string DriverKind;
    public readonly string SkillSelectionPolicy;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 10675819;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BrainId:" + BrainId + ","
        + "DecisionName:" + DecisionName + ","
        + "DriverKind:" + DriverKind + ","
        + "SkillSelectionPolicy:" + SkillSelectionPolicy + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

