
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRBuffs : Luban.BeanBase
{
    public DRBuffs(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ContinuousTagTemplateId = _buf.ReadInt();
        DispelBlockedByTagNames = _buf.ReadString();
        DispelCategory = _buf.ReadInt();
        DispelPolicy = _buf.ReadInt();
        DurationMs = _buf.ReadInt();
        IntervalMs = _buf.ReadInt();
        MaxStacks = _buf.ReadInt();
        Modifiers = _buf.ReadString();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); OnAddEffects = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnAddEffects.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OnIntervalEffects = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnIntervalEffects.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OnRemoveEffects = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnRemoveEffects.Add(_e0);}}
        PresentationTemplateId = _buf.ReadInt();
        RefreshPolicy = _buf.ReadInt();
        StackingPolicy = _buf.ReadInt();
        TagNames = _buf.ReadString();
        {int n0 = _buf.ReadSize(); TriggerIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TriggerIds.Add(_e0);}}
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRBuffs DeserializeDRBuffs(ByteBuf _buf)
    {
        return new DRBuffs(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly int ContinuousTagTemplateId;
    public readonly string DispelBlockedByTagNames;
    public readonly int DispelCategory;
    public readonly int DispelPolicy;
    public readonly int DurationMs;
    public readonly int IntervalMs;
    public readonly int MaxStacks;
    public readonly string Modifiers;
    public readonly string Name;
    public readonly System.Collections.Generic.List<int> OnAddEffects;
    public readonly System.Collections.Generic.List<int> OnIntervalEffects;
    public readonly System.Collections.Generic.List<int> OnRemoveEffects;
    public readonly int PresentationTemplateId;
    public readonly int RefreshPolicy;
    public readonly int StackingPolicy;
    public readonly string TagNames;
    public readonly System.Collections.Generic.List<int> TriggerIds;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -1662129518;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ContinuousTagTemplateId:" + ContinuousTagTemplateId + ","
        + "DispelBlockedByTagNames:" + DispelBlockedByTagNames + ","
        + "DispelCategory:" + DispelCategory + ","
        + "DispelPolicy:" + DispelPolicy + ","
        + "DurationMs:" + DurationMs + ","
        + "IntervalMs:" + IntervalMs + ","
        + "MaxStacks:" + MaxStacks + ","
        + "Modifiers:" + Modifiers + ","
        + "Name:" + Name + ","
        + "OnAddEffects:" + Luban.StringUtil.CollectionToString(OnAddEffects) + ","
        + "OnIntervalEffects:" + Luban.StringUtil.CollectionToString(OnIntervalEffects) + ","
        + "OnRemoveEffects:" + Luban.StringUtil.CollectionToString(OnRemoveEffects) + ","
        + "PresentationTemplateId:" + PresentationTemplateId + ","
        + "RefreshPolicy:" + RefreshPolicy + ","
        + "StackingPolicy:" + StackingPolicy + ","
        + "TagNames:" + TagNames + ","
        + "TriggerIds:" + Luban.StringUtil.CollectionToString(TriggerIds) + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

