
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRCharacters : Luban.BeanBase
{
    public DRCharacters(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AttributeTemplateId = _buf.ReadInt();
        ModelId = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); PassiveSkillIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PassiveSkillIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); SkillIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SkillIds.Add(_e0);}}
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRCharacters DeserializeDRCharacters(ByteBuf _buf)
    {
        return new DRCharacters(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly int AttributeTemplateId;
    public readonly int ModelId;
    public readonly string Name;
    public readonly System.Collections.Generic.List<int> PassiveSkillIds;
    public readonly System.Collections.Generic.List<int> SkillIds;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 2105456024;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AttributeTemplateId:" + AttributeTemplateId + ","
        + "ModelId:" + ModelId + ","
        + "Name:" + Name + ","
        + "PassiveSkillIds:" + Luban.StringUtil.CollectionToString(PassiveSkillIds) + ","
        + "SkillIds:" + Luban.StringUtil.CollectionToString(SkillIds) + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

