
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRContinuousProcesses : Luban.BeanBase
{
    public DRContinuousProcesses(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ContinuousTagTemplateId = _buf.ReadInt();
        DurationMs = _buf.ReadInt();
        IntervalMs = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); IntervalTriggerIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); IntervalTriggerIds.Add(_e0);}}
        Modifiers = _buf.ReadString();
        Name = _buf.ReadString();
        OutOfCombatSeconds = _buf.ReadInt();
        RequireOutOfCombat = _buf.ReadBool();
        {int n0 = _buf.ReadSize(); Tags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Tags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); TriggerIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TriggerIds.Add(_e0);}}
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRContinuousProcesses DeserializeDRContinuousProcesses(ByteBuf _buf)
    {
        return new DRContinuousProcesses(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly int ContinuousTagTemplateId;
    public readonly int DurationMs;
    public readonly int IntervalMs;
    public readonly System.Collections.Generic.List<int> IntervalTriggerIds;
    public readonly string Modifiers;
    public readonly string Name;
    public readonly int OutOfCombatSeconds;
    public readonly bool RequireOutOfCombat;
    public readonly System.Collections.Generic.List<int> Tags;
    public readonly System.Collections.Generic.List<int> TriggerIds;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -1202765408;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ContinuousTagTemplateId:" + ContinuousTagTemplateId + ","
        + "DurationMs:" + DurationMs + ","
        + "IntervalMs:" + IntervalMs + ","
        + "IntervalTriggerIds:" + Luban.StringUtil.CollectionToString(IntervalTriggerIds) + ","
        + "Modifiers:" + Modifiers + ","
        + "Name:" + Name + ","
        + "OutOfCombatSeconds:" + OutOfCombatSeconds + ","
        + "RequireOutOfCombat:" + RequireOutOfCombat + ","
        + "Tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "TriggerIds:" + Luban.StringUtil.CollectionToString(TriggerIds) + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

