
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRContinuousTagTemplates : Luban.BeanBase
{
    public DRContinuousTagTemplates(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); ActivationBlockedTags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ActivationBlockedTags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ActivationRequiredTags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ActivationRequiredTags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ApplicationTags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ApplicationTags.Add(_e0);}}
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); OngoingBlockedTags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); OngoingBlockedTags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OngoingRequiredTags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OngoingRequiredTags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); RemovalBlockedTags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RemovalBlockedTags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); RemovalRequiredTags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RemovalRequiredTags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); RemovalTags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RemovalTags.Add(_e0);}}
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRContinuousTagTemplates DeserializeDRContinuousTagTemplates(ByteBuf _buf)
    {
        return new DRContinuousTagTemplates(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly System.Collections.Generic.List<string> ActivationBlockedTags;
    public readonly System.Collections.Generic.List<int> ActivationRequiredTags;
    public readonly System.Collections.Generic.List<string> ApplicationTags;
    public readonly string Name;
    public readonly System.Collections.Generic.List<string> OngoingBlockedTags;
    public readonly System.Collections.Generic.List<int> OngoingRequiredTags;
    public readonly System.Collections.Generic.List<int> RemovalBlockedTags;
    public readonly System.Collections.Generic.List<int> RemovalRequiredTags;
    public readonly System.Collections.Generic.List<int> RemovalTags;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -163131492;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ActivationBlockedTags:" + Luban.StringUtil.CollectionToString(ActivationBlockedTags) + ","
        + "ActivationRequiredTags:" + Luban.StringUtil.CollectionToString(ActivationRequiredTags) + ","
        + "ApplicationTags:" + Luban.StringUtil.CollectionToString(ApplicationTags) + ","
        + "Name:" + Name + ","
        + "OngoingBlockedTags:" + Luban.StringUtil.CollectionToString(OngoingBlockedTags) + ","
        + "OngoingRequiredTags:" + Luban.StringUtil.CollectionToString(OngoingRequiredTags) + ","
        + "RemovalBlockedTags:" + Luban.StringUtil.CollectionToString(RemovalBlockedTags) + ","
        + "RemovalRequiredTags:" + Luban.StringUtil.CollectionToString(RemovalRequiredTags) + ","
        + "RemovalTags:" + Luban.StringUtil.CollectionToString(RemovalTags) + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

