
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRComponentTemplates : Luban.BeanBase
{
    public DRComponentTemplates(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Ops = _buf.ReadString();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRComponentTemplates DeserializeDRComponentTemplates(ByteBuf _buf)
    {
        return new DRComponentTemplates(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly string Name;
    public readonly string Ops;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 1009389546;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Ops:" + Ops + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

