
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DREffects : Luban.BeanBase
{
    public DREffects(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AttackRatio = _buf.ReadFloat();
        BaseDamage = _buf.ReadFloat();
        DamageType = _buf.ReadInt();
        EffectType = _buf.ReadInt();
        Name = _buf.ReadString();
        Radius = _buf.ReadFloat();
        TargetPolicy = _buf.ReadInt();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DREffects DeserializeDREffects(ByteBuf _buf)
    {
        return new DREffects(_buf);
    }

    /// <summary>
    /// Promoted from resource_documents.xlsx; edit this table as the source.
    /// </summary>
    public readonly int Id;
    public readonly float AttackRatio;
    public readonly float BaseDamage;
    public readonly int DamageType;
    public readonly int EffectType;
    public readonly string Name;
    public readonly float Radius;
    public readonly int TargetPolicy;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -1640567660;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AttackRatio:" + AttackRatio + ","
        + "BaseDamage:" + BaseDamage + ","
        + "DamageType:" + DamageType + ","
        + "EffectType:" + EffectType + ","
        + "Name:" + Name + ","
        + "Radius:" + Radius + ","
        + "TargetPolicy:" + TargetPolicy + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

