
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DREmitters : Luban.BeanBase
{
    public DREmitters(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CenterMode = _buf.ReadInt();
        CountPerShot = _buf.ReadInt();
        DelayMs = _buf.ReadInt();
        DurationMs = _buf.ReadInt();
        EmitKind = _buf.ReadInt();
        FanAngleDeg = _buf.ReadInt();
        IntervalMs = _buf.ReadInt();
        Name = _buf.ReadString();
        OffsetX = _buf.ReadInt();
        OffsetY = _buf.ReadInt();
        OffsetZ = _buf.ReadInt();
        TemplateId = _buf.ReadInt();
        TotalCount = _buf.ReadInt();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DREmitters DeserializeDREmitters(ByteBuf _buf)
    {
        return new DREmitters(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly int CenterMode;
    public readonly int CountPerShot;
    public readonly int DelayMs;
    public readonly int DurationMs;
    public readonly int EmitKind;
    public readonly int FanAngleDeg;
    public readonly int IntervalMs;
    public readonly string Name;
    public readonly int OffsetX;
    public readonly int OffsetY;
    public readonly int OffsetZ;
    public readonly int TemplateId;
    public readonly int TotalCount;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -1595166349;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "CenterMode:" + CenterMode + ","
        + "CountPerShot:" + CountPerShot + ","
        + "DelayMs:" + DelayMs + ","
        + "DurationMs:" + DurationMs + ","
        + "EmitKind:" + EmitKind + ","
        + "FanAngleDeg:" + FanAngleDeg + ","
        + "IntervalMs:" + IntervalMs + ","
        + "Name:" + Name + ","
        + "OffsetX:" + OffsetX + ","
        + "OffsetY:" + OffsetY + ","
        + "OffsetZ:" + OffsetZ + ","
        + "TemplateId:" + TemplateId + ","
        + "TotalCount:" + TotalCount + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

