
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRGameplays : Luban.BeanBase
{
    public DRGameplays(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DefaultDurationMs = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Tags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Tags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); TriggerIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TriggerIds.Add(_e0);}}
        WinPolicy = _buf.ReadInt();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRGameplays DeserializeDRGameplays(ByteBuf _buf)
    {
        return new DRGameplays(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly int DefaultDurationMs;
    public readonly string Name;
    public readonly System.Collections.Generic.List<int> Tags;
    public readonly System.Collections.Generic.List<int> TriggerIds;
    public readonly int WinPolicy;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -2142237153;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DefaultDurationMs:" + DefaultDurationMs + ","
        + "Name:" + Name + ","
        + "Tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "TriggerIds:" + Luban.StringUtil.CollectionToString(TriggerIds) + ","
        + "WinPolicy:" + WinPolicy + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

