
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRMotionGroups : Luban.BeanBase
{
    public DRMotionGroups(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DefaultPriority = _buf.ReadInt();
        Key = _buf.ReadString();
        Name = _buf.ReadString();
        Stacking = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); SuppressedGroupIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SuppressedGroupIds.Add(_e0);}}
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRMotionGroups DeserializeDRMotionGroups(ByteBuf _buf)
    {
        return new DRMotionGroups(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly int DefaultPriority;
    public readonly string Key;
    public readonly string Name;
    public readonly int Stacking;
    public readonly System.Collections.Generic.List<int> SuppressedGroupIds;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 184900824;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DefaultPriority:" + DefaultPriority + ","
        + "Key:" + Key + ","
        + "Name:" + Name + ","
        + "Stacking:" + Stacking + ","
        + "SuppressedGroupIds:" + Luban.StringUtil.CollectionToString(SuppressedGroupIds) + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

