
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRModels : Luban.BeanBase
{
    public DRModels(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        PrefabPath = _buf.ReadString();
        Scale = _buf.ReadFloat();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRModels DeserializeDRModels(ByteBuf _buf)
    {
        return new DRModels(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly string Name;
    public readonly string PrefabPath;
    public readonly float Scale;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 322911384;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "PrefabPath:" + PrefabPath + ","
        + "Scale:" + Scale + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

