
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRPassiveSkills : Luban.BeanBase
{
    public DRPassiveSkills(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); ContinuousProcessIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ContinuousProcessIds.Add(_e0);}}
        CooldownMs = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); TriggerIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TriggerIds.Add(_e0);}}
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRPassiveSkills DeserializeDRPassiveSkills(ByteBuf _buf)
    {
        return new DRPassiveSkills(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly System.Collections.Generic.List<int> ContinuousProcessIds;
    public readonly int CooldownMs;
    public readonly string Name;
    public readonly System.Collections.Generic.List<int> TriggerIds;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 1857527899;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ContinuousProcessIds:" + Luban.StringUtil.CollectionToString(ContinuousProcessIds) + ","
        + "CooldownMs:" + CooldownMs + ","
        + "Name:" + Name + ","
        + "TriggerIds:" + Luban.StringUtil.CollectionToString(TriggerIds) + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

