
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRPresentationTemplates : Luban.BeanBase
{
    public DRPresentationTemplates(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AssetId = _buf.ReadInt();
        AttachMode = _buf.ReadInt();
        ColorA = _buf.ReadFloat();
        ColorB = _buf.ReadFloat();
        ColorG = _buf.ReadFloat();
        ColorR = _buf.ReadFloat();
        DefaultDurationMs = _buf.ReadInt();
        Follow = _buf.ReadBool();
        Kind = _buf.ReadInt();
        Name = _buf.ReadString();
        OffsetX = _buf.ReadFloat();
        OffsetY = _buf.ReadFloat();
        OffsetZ = _buf.ReadFloat();
        Radius = _buf.ReadFloat();
        Scale = _buf.ReadFloat();
        Socket = _buf.ReadString();
        StackPolicy = _buf.ReadInt();
        StopPolicy = _buf.ReadInt();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRPresentationTemplates DeserializeDRPresentationTemplates(ByteBuf _buf)
    {
        return new DRPresentationTemplates(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly int AssetId;
    public readonly int AttachMode;
    public readonly float ColorA;
    public readonly float ColorB;
    public readonly float ColorG;
    public readonly float ColorR;
    public readonly int DefaultDurationMs;
    public readonly bool Follow;
    public readonly int Kind;
    public readonly string Name;
    public readonly float OffsetX;
    public readonly float OffsetY;
    public readonly float OffsetZ;
    public readonly float Radius;
    public readonly float Scale;
    public readonly string Socket;
    public readonly int StackPolicy;
    public readonly int StopPolicy;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 256773457;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AssetId:" + AssetId + ","
        + "AttachMode:" + AttachMode + ","
        + "ColorA:" + ColorA + ","
        + "ColorB:" + ColorB + ","
        + "ColorG:" + ColorG + ","
        + "ColorR:" + ColorR + ","
        + "DefaultDurationMs:" + DefaultDurationMs + ","
        + "Follow:" + Follow + ","
        + "Kind:" + Kind + ","
        + "Name:" + Name + ","
        + "OffsetX:" + OffsetX + ","
        + "OffsetY:" + OffsetY + ","
        + "OffsetZ:" + OffsetZ + ","
        + "Radius:" + Radius + ","
        + "Scale:" + Scale + ","
        + "Socket:" + Socket + ","
        + "StackPolicy:" + StackPolicy + ","
        + "StopPolicy:" + StopPolicy + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

