
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRProjectiles : Luban.BeanBase
{
    public DRProjectiles(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CollisionHeight = _buf.ReadFloat();
        CollisionLength = _buf.ReadFloat();
        CollisionWidth = _buf.ReadFloat();
        HitCooldownMs = _buf.ReadInt();
        HitPolicyKind = _buf.ReadInt();
        HitsRemaining = _buf.ReadInt();
        LifetimeMs = _buf.ReadInt();
        MaxDistance = _buf.ReadFloat();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); OnExitTriggerIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnExitTriggerIds.Add(_e0);}}
        OnExpireVfxId = _buf.ReadInt();
        OnHitEffectId = _buf.ReadInt();
        OnHitVfxId = _buf.ReadInt();
        OnSpawnVfxId = _buf.ReadInt();
        ReturnAfterMs = _buf.ReadInt();
        ReturnSpeed = _buf.ReadFloat();
        ReturnStopDistance = _buf.ReadFloat();
        SpawnRandomOffsetX = _buf.ReadFloat();
        SpawnRandomOffsetY = _buf.ReadInt();
        SpawnRandomOffsetZ = _buf.ReadFloat();
        Speed = _buf.ReadFloat();
        StateMachineProfileId = _buf.ReadString();
        TickIntervalMs = _buf.ReadInt();
        VfxId = _buf.ReadInt();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRProjectiles DeserializeDRProjectiles(ByteBuf _buf)
    {
        return new DRProjectiles(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly float CollisionHeight;
    public readonly float CollisionLength;
    public readonly float CollisionWidth;
    public readonly int HitCooldownMs;
    public readonly int HitPolicyKind;
    public readonly int HitsRemaining;
    public readonly int LifetimeMs;
    public readonly float MaxDistance;
    public readonly string Name;
    public readonly System.Collections.Generic.List<int> OnExitTriggerIds;
    public readonly int OnExpireVfxId;
    public readonly int OnHitEffectId;
    public readonly int OnHitVfxId;
    public readonly int OnSpawnVfxId;
    public readonly int ReturnAfterMs;
    public readonly float ReturnSpeed;
    public readonly float ReturnStopDistance;
    public readonly float SpawnRandomOffsetX;
    public readonly int SpawnRandomOffsetY;
    public readonly float SpawnRandomOffsetZ;
    public readonly float Speed;
    public readonly string StateMachineProfileId;
    public readonly int TickIntervalMs;
    public readonly int VfxId;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -48050628;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "CollisionHeight:" + CollisionHeight + ","
        + "CollisionLength:" + CollisionLength + ","
        + "CollisionWidth:" + CollisionWidth + ","
        + "HitCooldownMs:" + HitCooldownMs + ","
        + "HitPolicyKind:" + HitPolicyKind + ","
        + "HitsRemaining:" + HitsRemaining + ","
        + "LifetimeMs:" + LifetimeMs + ","
        + "MaxDistance:" + MaxDistance + ","
        + "Name:" + Name + ","
        + "OnExitTriggerIds:" + Luban.StringUtil.CollectionToString(OnExitTriggerIds) + ","
        + "OnExpireVfxId:" + OnExpireVfxId + ","
        + "OnHitEffectId:" + OnHitEffectId + ","
        + "OnHitVfxId:" + OnHitVfxId + ","
        + "OnSpawnVfxId:" + OnSpawnVfxId + ","
        + "ReturnAfterMs:" + ReturnAfterMs + ","
        + "ReturnSpeed:" + ReturnSpeed + ","
        + "ReturnStopDistance:" + ReturnStopDistance + ","
        + "SpawnRandomOffsetX:" + SpawnRandomOffsetX + ","
        + "SpawnRandomOffsetY:" + SpawnRandomOffsetY + ","
        + "SpawnRandomOffsetZ:" + SpawnRandomOffsetZ + ","
        + "Speed:" + Speed + ","
        + "StateMachineProfileId:" + StateMachineProfileId + ","
        + "TickIntervalMs:" + TickIntervalMs + ","
        + "VfxId:" + VfxId + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

