
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRProjectileLaunchers : Luban.BeanBase
{
    public DRProjectileLaunchers(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CountPerShot = _buf.ReadInt();
        DurationMs = _buf.ReadInt();
        EmitterType = _buf.ReadInt();
        FanAngleDeg = _buf.ReadInt();
        IntervalMs = _buf.ReadInt();
        Name = _buf.ReadString();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRProjectileLaunchers DeserializeDRProjectileLaunchers(ByteBuf _buf)
    {
        return new DRProjectileLaunchers(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly int CountPerShot;
    public readonly int DurationMs;
    public readonly int EmitterType;
    public readonly int FanAngleDeg;
    public readonly int IntervalMs;
    public readonly string Name;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 1089862012;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "CountPerShot:" + CountPerShot + ","
        + "DurationMs:" + DurationMs + ","
        + "EmitterType:" + EmitterType + ","
        + "FanAngleDeg:" + FanAngleDeg + ","
        + "IntervalMs:" + IntervalMs + ","
        + "Name:" + Name + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

