
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRResourceOngoingEffects : Luban.BeanBase
{
    public DRResourceOngoingEffects(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DurationMs = _buf.ReadInt();
        Name = _buf.ReadString();
        OnApplyEffectId = _buf.ReadInt();
        OnRemoveEffectId = _buf.ReadInt();
        OnTickEffectId = _buf.ReadInt();
        PeriodMs = _buf.ReadInt();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRResourceOngoingEffects DeserializeDRResourceOngoingEffects(ByteBuf _buf)
    {
        return new DRResourceOngoingEffects(_buf);
    }

    /// <summary>
    /// MOBA runtime resource; edit Excel as the source.
    /// </summary>
    public readonly int Id;
    public readonly int DurationMs;
    public readonly string Name;
    public readonly int OnApplyEffectId;
    public readonly int OnRemoveEffectId;
    public readonly int OnTickEffectId;
    public readonly int PeriodMs;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -272331037;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DurationMs:" + DurationMs + ","
        + "Name:" + Name + ","
        + "OnApplyEffectId:" + OnApplyEffectId + ","
        + "OnRemoveEffectId:" + OnRemoveEffectId + ","
        + "OnTickEffectId:" + OnTickEffectId + ","
        + "PeriodMs:" + PeriodMs + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

