
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRResourceBattleStart : Luban.BeanBase
{
    public DRResourceBattleStart(ByteBuf _buf) 
    {
        RowId = _buf.ReadInt();
        ClientId = _buf.ReadString();
        EnableClientPrediction = _buf.ReadBool();
        EnableDebug = _buf.ReadBool();
        EnableInputRecording = _buf.ReadBool();
        EnableInputReplay = _buf.ReadBool();
        InputDelayFrames = _buf.ReadInt();
        MaxPlayerCount = _buf.ReadInt();
        Name = _buf.ReadString();
        Network = _buf.ReadString();
        PlayerId = _buf.ReadString();
        Players = _buf.ReadString();
        RunMode = _buf.ReadString();
        SyncMode = _buf.ReadString();
        TickRate = _buf.ReadInt();
        WorldId = _buf.ReadString();
        WorldType = _buf.ReadString();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRResourceBattleStart DeserializeDRResourceBattleStart(ByteBuf _buf)
    {
        return new DRResourceBattleStart(_buf);
    }

    /// <summary>
    /// MOBA runtime resource; edit Excel as the source.
    /// </summary>
    public readonly int RowId;
    public readonly string ClientId;
    public readonly bool EnableClientPrediction;
    public readonly bool EnableDebug;
    public readonly bool EnableInputRecording;
    public readonly bool EnableInputReplay;
    public readonly int InputDelayFrames;
    public readonly int MaxPlayerCount;
    public readonly string Name;
    public readonly string Network;
    public readonly string PlayerId;
    public readonly string Players;
    public readonly string RunMode;
    public readonly string SyncMode;
    public readonly int TickRate;
    public readonly string WorldId;
    public readonly string WorldType;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 621497902;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "RowId:" + RowId + ","
        + "ClientId:" + ClientId + ","
        + "EnableClientPrediction:" + EnableClientPrediction + ","
        + "EnableDebug:" + EnableDebug + ","
        + "EnableInputRecording:" + EnableInputRecording + ","
        + "EnableInputReplay:" + EnableInputReplay + ","
        + "InputDelayFrames:" + InputDelayFrames + ","
        + "MaxPlayerCount:" + MaxPlayerCount + ","
        + "Name:" + Name + ","
        + "Network:" + Network + ","
        + "PlayerId:" + PlayerId + ","
        + "Players:" + Players + ","
        + "RunMode:" + RunMode + ","
        + "SyncMode:" + SyncMode + ","
        + "TickRate:" + TickRate + ","
        + "WorldId:" + WorldId + ","
        + "WorldType:" + WorldType + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

