
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRResourceActorStateMachines : Luban.BeanBase
{
    public DRResourceActorStateMachines(ByteBuf _buf) 
    {
        RowId = _buf.ReadInt();
        Id = _buf.ReadString();
        StartState = _buf.ReadString();
        States = _buf.ReadString();
        Transitions = _buf.ReadString();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRResourceActorStateMachines DeserializeDRResourceActorStateMachines(ByteBuf _buf)
    {
        return new DRResourceActorStateMachines(_buf);
    }

    /// <summary>
    /// MOBA runtime resource; edit Excel as the source.
    /// </summary>
    public readonly int RowId;
    public readonly string Id;
    public readonly string StartState;
    public readonly string States;
    public readonly string Transitions;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -2116276060;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "RowId:" + RowId + ","
        + "id:" + Id + ","
        + "startState:" + StartState + ","
        + "states:" + States + ","
        + "transitions:" + Transitions + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

