
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRResourceCharacterHfsm : Luban.BeanBase
{
    public DRResourceCharacterHfsm(ByteBuf _buf) 
    {
        RowId = _buf.ReadInt();
        DefinitionId = _buf.ReadString();
        FormatVersion = _buf.ReadInt();
        Machines = _buf.ReadString();
        RootMachineId = _buf.ReadString();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRResourceCharacterHfsm DeserializeDRResourceCharacterHfsm(ByteBuf _buf)
    {
        return new DRResourceCharacterHfsm(_buf);
    }

    /// <summary>
    /// MOBA runtime resource; edit Excel as the source.
    /// </summary>
    public readonly int RowId;
    public readonly string DefinitionId;
    public readonly int FormatVersion;
    public readonly string Machines;
    public readonly string RootMachineId;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -931068603;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "RowId:" + RowId + ","
        + "definitionId:" + DefinitionId + ","
        + "formatVersion:" + FormatVersion + ","
        + "machines:" + Machines + ","
        + "rootMachineId:" + RootMachineId + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

