
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRResourceDemoTbitem : Luban.BeanBase
{
    public DRResourceDemoTbitem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Count = _buf.ReadInt();
        Desc = _buf.ReadString();
        Name = _buf.ReadString();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRResourceDemoTbitem DeserializeDRResourceDemoTbitem(ByteBuf _buf)
    {
        return new DRResourceDemoTbitem(_buf);
    }

    /// <summary>
    /// MOBA runtime resource; edit Excel as the source.
    /// </summary>
    public readonly int Id;
    public readonly int Count;
    public readonly string Desc;
    public readonly string Name;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -960513504;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "count:" + Count + ","
        + "desc:" + Desc + ","
        + "name:" + Name + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

