
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRResourceAttributetemplates : Luban.BeanBase
{
    public DRResourceAttributetemplates(ByteBuf _buf) 
    {
        Code = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); ActiveSkills = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ActiveSkills.Add(_e0);}}
        AttackRange = _buf.ReadInt();
        AttackSpeedR = _buf.ReadInt();
        CooldownReduceR = _buf.ReadInt();
        CriticalR = _buf.ReadInt();
        ExtraHp = _buf.ReadInt();
        ExtraMagicAttack = _buf.ReadInt();
        ExtraPhysicsAttack = _buf.ReadInt();
        Hp = _buf.ReadInt();
        MagicAttack = _buf.ReadInt();
        MagicBloodsuckingR = _buf.ReadInt();
        MagicDefense = _buf.ReadInt();
        MagicPenetrationR = _buf.ReadInt();
        Mana = _buf.ReadInt();
        MaxHp = _buf.ReadInt();
        MaxMana = _buf.ReadInt();
        MoveSpeed = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); PassiveSkills = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PassiveSkills.Add(_e0);}}
        PerSecondBloodR = _buf.ReadInt();
        PerSecondManaR = _buf.ReadInt();
        PhysicsAttack = _buf.ReadInt();
        PhysicsBloodsuckingR = _buf.ReadInt();
        PhysicsDefense = _buf.ReadInt();
        PhysicsPenetrationR = _buf.ReadInt();
        ResilienceR = _buf.ReadInt();
        UpgradeCode = _buf.ReadInt();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRResourceAttributetemplates DeserializeDRResourceAttributetemplates(ByteBuf _buf)
    {
        return new DRResourceAttributetemplates(_buf);
    }

    /// <summary>
    /// MOBA runtime resource; edit Excel as the source.
    /// </summary>
    public readonly int Code;
    public readonly System.Collections.Generic.List<int> ActiveSkills;
    public readonly int AttackRange;
    public readonly int AttackSpeedR;
    public readonly int CooldownReduceR;
    public readonly int CriticalR;
    public readonly int ExtraHp;
    public readonly int ExtraMagicAttack;
    public readonly int ExtraPhysicsAttack;
    public readonly int Hp;
    public readonly int MagicAttack;
    public readonly int MagicBloodsuckingR;
    public readonly int MagicDefense;
    public readonly int MagicPenetrationR;
    public readonly int Mana;
    public readonly int MaxHp;
    public readonly int MaxMana;
    public readonly int MoveSpeed;
    public readonly string Name;
    public readonly System.Collections.Generic.List<int> PassiveSkills;
    public readonly int PerSecondBloodR;
    public readonly int PerSecondManaR;
    public readonly int PhysicsAttack;
    public readonly int PhysicsBloodsuckingR;
    public readonly int PhysicsDefense;
    public readonly int PhysicsPenetrationR;
    public readonly int ResilienceR;
    public readonly int UpgradeCode;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -1237184519;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Code:" + Code + ","
        + "ActiveSkills:" + Luban.StringUtil.CollectionToString(ActiveSkills) + ","
        + "AttackRange:" + AttackRange + ","
        + "AttackSpeedR:" + AttackSpeedR + ","
        + "CooldownReduceR:" + CooldownReduceR + ","
        + "CriticalR:" + CriticalR + ","
        + "ExtraHp:" + ExtraHp + ","
        + "ExtraMagicAttack:" + ExtraMagicAttack + ","
        + "ExtraPhysicsAttack:" + ExtraPhysicsAttack + ","
        + "Hp:" + Hp + ","
        + "MagicAttack:" + MagicAttack + ","
        + "MagicBloodsuckingR:" + MagicBloodsuckingR + ","
        + "MagicDefense:" + MagicDefense + ","
        + "MagicPenetrationR:" + MagicPenetrationR + ","
        + "Mana:" + Mana + ","
        + "MaxHp:" + MaxHp + ","
        + "MaxMana:" + MaxMana + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "Name:" + Name + ","
        + "PassiveSkills:" + Luban.StringUtil.CollectionToString(PassiveSkills) + ","
        + "PerSecondBloodR:" + PerSecondBloodR + ","
        + "PerSecondManaR:" + PerSecondManaR + ","
        + "PhysicsAttack:" + PhysicsAttack + ","
        + "PhysicsBloodsuckingR:" + PhysicsBloodsuckingR + ","
        + "PhysicsDefense:" + PhysicsDefense + ","
        + "PhysicsPenetrationR:" + PhysicsPenetrationR + ","
        + "ResilienceR:" + ResilienceR + ","
        + "UpgradeCode:" + UpgradeCode + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

