
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRResourceDtbuff : Luban.BeanBase
{
    public DRResourceDtbuff(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DurationMs = _buf.ReadInt();
        IntervalMs = _buf.ReadInt();
        MaxStacks = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); OnAddEffects = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnAddEffects.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OnIntervalEffects = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnIntervalEffects.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OnRemoveEffects = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnRemoveEffects.Add(_e0);}}
        RefreshPolicy = _buf.ReadInt();
        StackingPolicy = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Tags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Tags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); TriggerIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TriggerIds.Add(_e0);}}
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRResourceDtbuff DeserializeDRResourceDtbuff(ByteBuf _buf)
    {
        return new DRResourceDtbuff(_buf);
    }

    /// <summary>
    /// MOBA runtime resource; edit Excel as the source.
    /// </summary>
    public readonly int Id;
    public readonly int DurationMs;
    public readonly int IntervalMs;
    public readonly int MaxStacks;
    public readonly string Name;
    public readonly System.Collections.Generic.List<int> OnAddEffects;
    public readonly System.Collections.Generic.List<int> OnIntervalEffects;
    public readonly System.Collections.Generic.List<int> OnRemoveEffects;
    public readonly int RefreshPolicy;
    public readonly int StackingPolicy;
    public readonly System.Collections.Generic.List<int> Tags;
    public readonly System.Collections.Generic.List<int> TriggerIds;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 1531463359;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DurationMs:" + DurationMs + ","
        + "IntervalMs:" + IntervalMs + ","
        + "MaxStacks:" + MaxStacks + ","
        + "Name:" + Name + ","
        + "OnAddEffects:" + Luban.StringUtil.CollectionToString(OnAddEffects) + ","
        + "OnIntervalEffects:" + Luban.StringUtil.CollectionToString(OnIntervalEffects) + ","
        + "OnRemoveEffects:" + Luban.StringUtil.CollectionToString(OnRemoveEffects) + ","
        + "RefreshPolicy:" + RefreshPolicy + ","
        + "StackingPolicy:" + StackingPolicy + ","
        + "Tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "TriggerIds:" + Luban.StringUtil.CollectionToString(TriggerIds) + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

