
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRResourceCharacterViewActions : Luban.BeanBase
{
    public DRResourceCharacterViewActions(ByteBuf _buf) 
    {
        RowId = _buf.ReadInt();
        SchemaVersion = _buf.ReadInt();
        States = _buf.ReadString();
        Variants = _buf.ReadString();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRResourceCharacterViewActions DeserializeDRResourceCharacterViewActions(ByteBuf _buf)
    {
        return new DRResourceCharacterViewActions(_buf);
    }

    /// <summary>
    /// MOBA runtime resource; edit Excel as the source.
    /// </summary>
    public readonly int RowId;
    public readonly int SchemaVersion;
    public readonly string States;
    public readonly string Variants;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 1280646283;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "RowId:" + RowId + ","
        + "schemaVersion:" + SchemaVersion + ","
        + "states:" + States + ","
        + "variants:" + Variants + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

