
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRResourceEffectPlans : Luban.BeanBase
{
    public DRResourceEffectPlans(ByteBuf _buf) 
    {
        RowId = _buf.ReadInt();
        Strings = _buf.ReadString();
        Triggers = _buf.ReadString();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRResourceEffectPlans DeserializeDRResourceEffectPlans(ByteBuf _buf)
    {
        return new DRResourceEffectPlans(_buf);
    }

    /// <summary>
    /// MOBA runtime resource; edit Excel as the source.
    /// </summary>
    public readonly int RowId;
    public readonly string Strings;
    public readonly string Triggers;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -1265919235;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "RowId:" + RowId + ","
        + "Strings:" + Strings + ","
        + "Triggers:" + Triggers + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

