
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRSearchQueryTemplates : Luban.BeanBase
{
    public DRSearchQueryTemplates(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ExplicitTargetPolicy = _buf.ReadInt();
        MaxCount = _buf.ReadInt();
        Name = _buf.ReadString();
        Provider = _buf.ReadString();
        Rules = _buf.ReadString();
        Scorers = _buf.ReadString();
        Selector = _buf.ReadString();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRSearchQueryTemplates DeserializeDRSearchQueryTemplates(ByteBuf _buf)
    {
        return new DRSearchQueryTemplates(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly int ExplicitTargetPolicy;
    public readonly int MaxCount;
    public readonly string Name;
    public readonly string Provider;
    public readonly string Rules;
    public readonly string Scorers;
    public readonly string Selector;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 1508950215;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ExplicitTargetPolicy:" + ExplicitTargetPolicy + ","
        + "MaxCount:" + MaxCount + ","
        + "Name:" + Name + ","
        + "Provider:" + Provider + ","
        + "Rules:" + Rules + ","
        + "Scorers:" + Scorers + ","
        + "Selector:" + Selector + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

