
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRSkillLevelTables : Luban.BeanBase
{
    public DRSkillLevelTables(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Levels = _buf.ReadString();
        {int n0 = _buf.ReadSize(); ParamNames = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ParamNames.Add(_e0);}}
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRSkillLevelTables DeserializeDRSkillLevelTables(ByteBuf _buf)
    {
        return new DRSkillLevelTables(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly string Levels;
    public readonly System.Collections.Generic.List<string> ParamNames;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 244806822;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Levels:" + Levels + ","
        + "ParamNames:" + Luban.StringUtil.CollectionToString(ParamNames) + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

