
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRSkillButtonTemplates : Luban.BeanBase
{
    public DRSkillButtonTemplates(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AimMaxRadius = _buf.ReadFloat();
        AimMode = _buf.ReadInt();
        DragThreshold = _buf.ReadFloat();
        EnableAim = _buf.ReadBool();
        FaceToAim = _buf.ReadBool();
        IndicatorShape = _buf.ReadInt();
        IndicatorWorldWidth = _buf.ReadFloat();
        LongPressSeconds = _buf.ReadFloat();
        Name = _buf.ReadString();
        SelectRange = _buf.ReadFloat();
        SelfRadius = _buf.ReadFloat();
        UsePointMode = _buf.ReadInt();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRSkillButtonTemplates DeserializeDRSkillButtonTemplates(ByteBuf _buf)
    {
        return new DRSkillButtonTemplates(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly float AimMaxRadius;
    public readonly int AimMode;
    public readonly float DragThreshold;
    public readonly bool EnableAim;
    public readonly bool FaceToAim;
    public readonly int IndicatorShape;
    public readonly float IndicatorWorldWidth;
    public readonly float LongPressSeconds;
    public readonly string Name;
    public readonly float SelectRange;
    public readonly float SelfRadius;
    public readonly int UsePointMode;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 240254788;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AimMaxRadius:" + AimMaxRadius + ","
        + "AimMode:" + AimMode + ","
        + "DragThreshold:" + DragThreshold + ","
        + "EnableAim:" + EnableAim + ","
        + "FaceToAim:" + FaceToAim + ","
        + "IndicatorShape:" + IndicatorShape + ","
        + "IndicatorWorldWidth:" + IndicatorWorldWidth + ","
        + "LongPressSeconds:" + LongPressSeconds + ","
        + "Name:" + Name + ","
        + "SelectRange:" + SelectRange + ","
        + "SelfRadius:" + SelfRadius + ","
        + "UsePointMode:" + UsePointMode + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

