
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRSkills : Luban.BeanBase
{
    public DRSkills(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CastFlowId = _buf.ReadInt();
        Category = _buf.ReadInt();
        CooldownMs = _buf.ReadInt();
        IconId = _buf.ReadInt();
        LevelTableId = _buf.ReadInt();
        Name = _buf.ReadString();
        PreCastFlowId = _buf.ReadInt();
        Range = _buf.ReadInt();
        RequiredTargetQueryId = _buf.ReadInt();
        SkillButtonTemplateId = _buf.ReadInt();
        SkillType = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Tags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Tags.Add(_e0);}}
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRSkills DeserializeDRSkills(ByteBuf _buf)
    {
        return new DRSkills(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly int CastFlowId;
    public readonly int Category;
    public readonly int CooldownMs;
    public readonly int IconId;
    public readonly int LevelTableId;
    public readonly string Name;
    public readonly int PreCastFlowId;
    public readonly int Range;
    public readonly int RequiredTargetQueryId;
    public readonly int SkillButtonTemplateId;
    public readonly int SkillType;
    public readonly System.Collections.Generic.List<int> Tags;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 491147888;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "CastFlowId:" + CastFlowId + ","
        + "Category:" + Category + ","
        + "CooldownMs:" + CooldownMs + ","
        + "IconId:" + IconId + ","
        + "LevelTableId:" + LevelTableId + ","
        + "Name:" + Name + ","
        + "PreCastFlowId:" + PreCastFlowId + ","
        + "Range:" + Range + ","
        + "RequiredTargetQueryId:" + RequiredTargetQueryId + ","
        + "SkillButtonTemplateId:" + SkillButtonTemplateId + ","
        + "SkillType:" + SkillType + ","
        + "Tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

