
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRSkillFlows : Luban.BeanBase
{
    public DRSkillFlows(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Phases = _buf.ReadString();
        PipelineContinuousTagTemplateId = _buf.ReadInt();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRSkillFlows DeserializeDRSkillFlows(ByteBuf _buf)
    {
        return new DRSkillFlows(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly string Name;
    public readonly string Phases;
    public readonly int PipelineContinuousTagTemplateId;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -1850720158;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Phases:" + Phases + ","
        + "PipelineContinuousTagTemplateId:" + PipelineContinuousTagTemplateId + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

