
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRSpawnSummonActionTemplates : Luban.BeanBase
{
    public DRSpawnSummonActionTemplates(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ArcAngleDeg = _buf.ReadInt();
        GridCols = _buf.ReadInt();
        GridRows = _buf.ReadInt();
        GridSpacingX = _buf.ReadInt();
        GridSpacingZ = _buf.ReadInt();
        IntervalMs = _buf.ReadInt();
        Name = _buf.ReadString();
        OwnerKeyMode = _buf.ReadInt();
        PatternCount = _buf.ReadInt();
        PatternMode = _buf.ReadInt();
        PerPointRotationMode = _buf.ReadInt();
        PerPointYawOffsetDeg = _buf.ReadInt();
        PositionMode = _buf.ReadInt();
        Radius = _buf.ReadInt();
        RandomRadiusMax = _buf.ReadInt();
        RandomRadiusMin = _buf.ReadInt();
        RandomSeed = _buf.ReadInt();
        RotationMode = _buf.ReadInt();
        Spacing = _buf.ReadFloat();
        StartAngleDeg = _buf.ReadInt();
        SummonId = _buf.ReadInt();
        TargetMode = _buf.ReadInt();
        YawOffsetDeg = _buf.ReadInt();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRSpawnSummonActionTemplates DeserializeDRSpawnSummonActionTemplates(ByteBuf _buf)
    {
        return new DRSpawnSummonActionTemplates(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly int ArcAngleDeg;
    public readonly int GridCols;
    public readonly int GridRows;
    public readonly int GridSpacingX;
    public readonly int GridSpacingZ;
    public readonly int IntervalMs;
    public readonly string Name;
    public readonly int OwnerKeyMode;
    public readonly int PatternCount;
    public readonly int PatternMode;
    public readonly int PerPointRotationMode;
    public readonly int PerPointYawOffsetDeg;
    public readonly int PositionMode;
    public readonly int Radius;
    public readonly int RandomRadiusMax;
    public readonly int RandomRadiusMin;
    public readonly int RandomSeed;
    public readonly int RotationMode;
    public readonly float Spacing;
    public readonly int StartAngleDeg;
    public readonly int SummonId;
    public readonly int TargetMode;
    public readonly int YawOffsetDeg;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = 2126270709;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ArcAngleDeg:" + ArcAngleDeg + ","
        + "GridCols:" + GridCols + ","
        + "GridRows:" + GridRows + ","
        + "GridSpacingX:" + GridSpacingX + ","
        + "GridSpacingZ:" + GridSpacingZ + ","
        + "IntervalMs:" + IntervalMs + ","
        + "Name:" + Name + ","
        + "OwnerKeyMode:" + OwnerKeyMode + ","
        + "PatternCount:" + PatternCount + ","
        + "PatternMode:" + PatternMode + ","
        + "PerPointRotationMode:" + PerPointRotationMode + ","
        + "PerPointYawOffsetDeg:" + PerPointYawOffsetDeg + ","
        + "PositionMode:" + PositionMode + ","
        + "Radius:" + Radius + ","
        + "RandomRadiusMax:" + RandomRadiusMax + ","
        + "RandomRadiusMin:" + RandomRadiusMin + ","
        + "RandomSeed:" + RandomSeed + ","
        + "RotationMode:" + RotationMode + ","
        + "Spacing:" + Spacing + ","
        + "StartAngleDeg:" + StartAngleDeg + ","
        + "SummonId:" + SummonId + ","
        + "TargetMode:" + TargetMode + ","
        + "YawOffsetDeg:" + YawOffsetDeg + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

