
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRSummons : Luban.BeanBase
{
    public DRSummons(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); AttrScales = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AttrScales.Add(_e0);}}
        AttributeTemplateId = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); DefaultComponentTemplateIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); DefaultComponentTemplateIds.Add(_e0);}}
        DespawnOnOwnerDie = _buf.ReadBool();
        LifetimeMs = _buf.ReadInt();
        MaxAlivePerOwner = _buf.ReadInt();
        ModelId = _buf.ReadInt();
        Name = _buf.ReadString();
        OverflowPolicy = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); PassiveSkillIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); PassiveSkillIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); SkillIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SkillIds.Add(_e0);}}
        StatsMode = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Tags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Tags.Add(_e0);}}
        UnitSubType = _buf.ReadInt();
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRSummons DeserializeDRSummons(ByteBuf _buf)
    {
        return new DRSummons(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly System.Collections.Generic.List<int> AttrScales;
    public readonly int AttributeTemplateId;
    public readonly System.Collections.Generic.List<int> DefaultComponentTemplateIds;
    public readonly bool DespawnOnOwnerDie;
    public readonly int LifetimeMs;
    public readonly int MaxAlivePerOwner;
    public readonly int ModelId;
    public readonly string Name;
    public readonly int OverflowPolicy;
    public readonly System.Collections.Generic.List<int> PassiveSkillIds;
    public readonly System.Collections.Generic.List<int> SkillIds;
    public readonly int StatsMode;
    public readonly System.Collections.Generic.List<int> Tags;
    public readonly int UnitSubType;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -1664266428;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AttrScales:" + Luban.StringUtil.CollectionToString(AttrScales) + ","
        + "AttributeTemplateId:" + AttributeTemplateId + ","
        + "DefaultComponentTemplateIds:" + Luban.StringUtil.CollectionToString(DefaultComponentTemplateIds) + ","
        + "DespawnOnOwnerDie:" + DespawnOnOwnerDie + ","
        + "LifetimeMs:" + LifetimeMs + ","
        + "MaxAlivePerOwner:" + MaxAlivePerOwner + ","
        + "ModelId:" + ModelId + ","
        + "Name:" + Name + ","
        + "OverflowPolicy:" + OverflowPolicy + ","
        + "PassiveSkillIds:" + Luban.StringUtil.CollectionToString(PassiveSkillIds) + ","
        + "SkillIds:" + Luban.StringUtil.CollectionToString(SkillIds) + ","
        + "StatsMode:" + StatsMode + ","
        + "Tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "UnitSubType:" + UnitSubType + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

