
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public sealed partial class DRTagTemplates : Luban.BeanBase
{
    public DRTagTemplates(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); BlockedTags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BlockedTags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); GrantTags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); GrantTags.Add(_e0);}}
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); RemoveTags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RemoveTags.Add(_e0);}}
        {int n0 = _buf.ReadSize(); RequiredTags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RequiredTags.Add(_e0);}}
        OmittedFields = _buf.ReadString();
        NullFields = _buf.ReadString();
    }

    public static DRTagTemplates DeserializeDRTagTemplates(ByteBuf _buf)
    {
        return new DRTagTemplates(_buf);
    }

    /// <summary>
    /// Generated once from the runtime JSON baseline; edit Excel after migration.
    /// </summary>
    public readonly int Id;
    public readonly System.Collections.Generic.List<int> BlockedTags;
    public readonly System.Collections.Generic.List<int> GrantTags;
    public readonly string Name;
    public readonly System.Collections.Generic.List<int> RemoveTags;
    public readonly System.Collections.Generic.List<int> RequiredTags;
    public readonly string OmittedFields;
    public readonly string NullFields;
   
    public const int __ID__ = -1930360723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BlockedTags:" + Luban.StringUtil.CollectionToString(BlockedTags) + ","
        + "GrantTags:" + Luban.StringUtil.CollectionToString(GrantTags) + ","
        + "Name:" + Name + ","
        + "RemoveTags:" + Luban.StringUtil.CollectionToString(RemoveTags) + ","
        + "RequiredTags:" + Luban.StringUtil.CollectionToString(RequiredTags) + ","
        + "OmittedFields:" + OmittedFields + ","
        + "NullFields:" + NullFields + ","
        + "}";
    }
}
}

