
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class Effects
{
    private readonly System.Collections.Generic.Dictionary<int, DREffects> _dataMap;
    private readonly System.Collections.Generic.List<DREffects> _dataList;
    
    public Effects(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DREffects>(n);
        _dataList = new System.Collections.Generic.List<DREffects>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DREffects _v;
            _v = global::moba_luban.DREffects.DeserializeDREffects(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DREffects> DataMap => _dataMap;
    public System.Collections.Generic.List<DREffects> DataList => _dataList;

    public DREffects GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DREffects Get(int key) => _dataMap[key];
    public DREffects this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

