
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class Emitters
{
    private readonly System.Collections.Generic.Dictionary<int, DREmitters> _dataMap;
    private readonly System.Collections.Generic.List<DREmitters> _dataList;
    
    public Emitters(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DREmitters>(n);
        _dataList = new System.Collections.Generic.List<DREmitters>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DREmitters _v;
            _v = global::moba_luban.DREmitters.DeserializeDREmitters(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DREmitters> DataMap => _dataMap;
    public System.Collections.Generic.List<DREmitters> DataList => _dataList;

    public DREmitters GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DREmitters Get(int key) => _dataMap[key];
    public DREmitters this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

