
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class Gameplays
{
    private readonly System.Collections.Generic.Dictionary<int, DRGameplays> _dataMap;
    private readonly System.Collections.Generic.List<DRGameplays> _dataList;
    
    public Gameplays(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRGameplays>(n);
        _dataList = new System.Collections.Generic.List<DRGameplays>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRGameplays _v;
            _v = global::moba_luban.DRGameplays.DeserializeDRGameplays(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRGameplays> DataMap => _dataMap;
    public System.Collections.Generic.List<DRGameplays> DataList => _dataList;

    public DRGameplays GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRGameplays Get(int key) => _dataMap[key];
    public DRGameplays this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

