
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class Models
{
    private readonly System.Collections.Generic.Dictionary<int, DRModels> _dataMap;
    private readonly System.Collections.Generic.List<DRModels> _dataList;
    
    public Models(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRModels>(n);
        _dataList = new System.Collections.Generic.List<DRModels>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRModels _v;
            _v = global::moba_luban.DRModels.DeserializeDRModels(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRModels> DataMap => _dataMap;
    public System.Collections.Generic.List<DRModels> DataList => _dataList;

    public DRModels GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRModels Get(int key) => _dataMap[key];
    public DRModels this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

