
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class MotionGroups
{
    private readonly System.Collections.Generic.Dictionary<int, DRMotionGroups> _dataMap;
    private readonly System.Collections.Generic.List<DRMotionGroups> _dataList;
    
    public MotionGroups(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRMotionGroups>(n);
        _dataList = new System.Collections.Generic.List<DRMotionGroups>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRMotionGroups _v;
            _v = global::moba_luban.DRMotionGroups.DeserializeDRMotionGroups(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRMotionGroups> DataMap => _dataMap;
    public System.Collections.Generic.List<DRMotionGroups> DataList => _dataList;

    public DRMotionGroups GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRMotionGroups Get(int key) => _dataMap[key];
    public DRMotionGroups this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

