
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class PassiveSkills
{
    private readonly System.Collections.Generic.Dictionary<int, DRPassiveSkills> _dataMap;
    private readonly System.Collections.Generic.List<DRPassiveSkills> _dataList;
    
    public PassiveSkills(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRPassiveSkills>(n);
        _dataList = new System.Collections.Generic.List<DRPassiveSkills>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRPassiveSkills _v;
            _v = global::moba_luban.DRPassiveSkills.DeserializeDRPassiveSkills(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRPassiveSkills> DataMap => _dataMap;
    public System.Collections.Generic.List<DRPassiveSkills> DataList => _dataList;

    public DRPassiveSkills GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRPassiveSkills Get(int key) => _dataMap[key];
    public DRPassiveSkills this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

