
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class PresentationTemplates
{
    private readonly System.Collections.Generic.Dictionary<int, DRPresentationTemplates> _dataMap;
    private readonly System.Collections.Generic.List<DRPresentationTemplates> _dataList;
    
    public PresentationTemplates(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRPresentationTemplates>(n);
        _dataList = new System.Collections.Generic.List<DRPresentationTemplates>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRPresentationTemplates _v;
            _v = global::moba_luban.DRPresentationTemplates.DeserializeDRPresentationTemplates(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRPresentationTemplates> DataMap => _dataMap;
    public System.Collections.Generic.List<DRPresentationTemplates> DataList => _dataList;

    public DRPresentationTemplates GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRPresentationTemplates Get(int key) => _dataMap[key];
    public DRPresentationTemplates this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

