
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class Projectiles
{
    private readonly System.Collections.Generic.Dictionary<int, DRProjectiles> _dataMap;
    private readonly System.Collections.Generic.List<DRProjectiles> _dataList;
    
    public Projectiles(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRProjectiles>(n);
        _dataList = new System.Collections.Generic.List<DRProjectiles>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRProjectiles _v;
            _v = global::moba_luban.DRProjectiles.DeserializeDRProjectiles(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRProjectiles> DataMap => _dataMap;
    public System.Collections.Generic.List<DRProjectiles> DataList => _dataList;

    public DRProjectiles GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRProjectiles Get(int key) => _dataMap[key];
    public DRProjectiles this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

