
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class ProjectileLaunchers
{
    private readonly System.Collections.Generic.Dictionary<int, DRProjectileLaunchers> _dataMap;
    private readonly System.Collections.Generic.List<DRProjectileLaunchers> _dataList;
    
    public ProjectileLaunchers(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRProjectileLaunchers>(n);
        _dataList = new System.Collections.Generic.List<DRProjectileLaunchers>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRProjectileLaunchers _v;
            _v = global::moba_luban.DRProjectileLaunchers.DeserializeDRProjectileLaunchers(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRProjectileLaunchers> DataMap => _dataMap;
    public System.Collections.Generic.List<DRProjectileLaunchers> DataList => _dataList;

    public DRProjectileLaunchers GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRProjectileLaunchers Get(int key) => _dataMap[key];
    public DRProjectileLaunchers this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

