
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class ResourceOngoingEffects
{
    private readonly System.Collections.Generic.Dictionary<int, DRResourceOngoingEffects> _dataMap;
    private readonly System.Collections.Generic.List<DRResourceOngoingEffects> _dataList;
    
    public ResourceOngoingEffects(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRResourceOngoingEffects>(n);
        _dataList = new System.Collections.Generic.List<DRResourceOngoingEffects>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRResourceOngoingEffects _v;
            _v = global::moba_luban.DRResourceOngoingEffects.DeserializeDRResourceOngoingEffects(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRResourceOngoingEffects> DataMap => _dataMap;
    public System.Collections.Generic.List<DRResourceOngoingEffects> DataList => _dataList;

    public DRResourceOngoingEffects GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRResourceOngoingEffects Get(int key) => _dataMap[key];
    public DRResourceOngoingEffects this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

