
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class ResourceCharacterHfsm
{
    private readonly System.Collections.Generic.Dictionary<int, DRResourceCharacterHfsm> _dataMap;
    private readonly System.Collections.Generic.List<DRResourceCharacterHfsm> _dataList;
    
    public ResourceCharacterHfsm(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRResourceCharacterHfsm>(n);
        _dataList = new System.Collections.Generic.List<DRResourceCharacterHfsm>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRResourceCharacterHfsm _v;
            _v = global::moba_luban.DRResourceCharacterHfsm.DeserializeDRResourceCharacterHfsm(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RowId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRResourceCharacterHfsm> DataMap => _dataMap;
    public System.Collections.Generic.List<DRResourceCharacterHfsm> DataList => _dataList;

    public DRResourceCharacterHfsm GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRResourceCharacterHfsm Get(int key) => _dataMap[key];
    public DRResourceCharacterHfsm this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

