
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class ResourceCharacterViewActions
{
    private readonly System.Collections.Generic.Dictionary<int, DRResourceCharacterViewActions> _dataMap;
    private readonly System.Collections.Generic.List<DRResourceCharacterViewActions> _dataList;
    
    public ResourceCharacterViewActions(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRResourceCharacterViewActions>(n);
        _dataList = new System.Collections.Generic.List<DRResourceCharacterViewActions>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRResourceCharacterViewActions _v;
            _v = global::moba_luban.DRResourceCharacterViewActions.DeserializeDRResourceCharacterViewActions(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RowId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRResourceCharacterViewActions> DataMap => _dataMap;
    public System.Collections.Generic.List<DRResourceCharacterViewActions> DataList => _dataList;

    public DRResourceCharacterViewActions GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRResourceCharacterViewActions Get(int key) => _dataMap[key];
    public DRResourceCharacterViewActions this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

