
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class ResourceAttributetemplates
{
    private readonly System.Collections.Generic.Dictionary<int, DRResourceAttributetemplates> _dataMap;
    private readonly System.Collections.Generic.List<DRResourceAttributetemplates> _dataList;
    
    public ResourceAttributetemplates(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRResourceAttributetemplates>(n);
        _dataList = new System.Collections.Generic.List<DRResourceAttributetemplates>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRResourceAttributetemplates _v;
            _v = global::moba_luban.DRResourceAttributetemplates.DeserializeDRResourceAttributetemplates(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Code, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRResourceAttributetemplates> DataMap => _dataMap;
    public System.Collections.Generic.List<DRResourceAttributetemplates> DataList => _dataList;

    public DRResourceAttributetemplates GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRResourceAttributetemplates Get(int key) => _dataMap[key];
    public DRResourceAttributetemplates this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

