
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class ResourceEffectPlans
{
    private readonly System.Collections.Generic.Dictionary<int, DRResourceEffectPlans> _dataMap;
    private readonly System.Collections.Generic.List<DRResourceEffectPlans> _dataList;
    
    public ResourceEffectPlans(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRResourceEffectPlans>(n);
        _dataList = new System.Collections.Generic.List<DRResourceEffectPlans>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRResourceEffectPlans _v;
            _v = global::moba_luban.DRResourceEffectPlans.DeserializeDRResourceEffectPlans(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RowId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRResourceEffectPlans> DataMap => _dataMap;
    public System.Collections.Generic.List<DRResourceEffectPlans> DataList => _dataList;

    public DRResourceEffectPlans GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRResourceEffectPlans Get(int key) => _dataMap[key];
    public DRResourceEffectPlans this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

