
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class ResourceDtbuff
{
    private readonly System.Collections.Generic.Dictionary<int, DRResourceDtbuff> _dataMap;
    private readonly System.Collections.Generic.List<DRResourceDtbuff> _dataList;
    
    public ResourceDtbuff(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRResourceDtbuff>(n);
        _dataList = new System.Collections.Generic.List<DRResourceDtbuff>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRResourceDtbuff _v;
            _v = global::moba_luban.DRResourceDtbuff.DeserializeDRResourceDtbuff(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRResourceDtbuff> DataMap => _dataMap;
    public System.Collections.Generic.List<DRResourceDtbuff> DataList => _dataList;

    public DRResourceDtbuff GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRResourceDtbuff Get(int key) => _dataMap[key];
    public DRResourceDtbuff this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

