
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class ResourceDemoTbitem
{
    private readonly System.Collections.Generic.Dictionary<int, DRResourceDemoTbitem> _dataMap;
    private readonly System.Collections.Generic.List<DRResourceDemoTbitem> _dataList;
    
    public ResourceDemoTbitem(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRResourceDemoTbitem>(n);
        _dataList = new System.Collections.Generic.List<DRResourceDemoTbitem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRResourceDemoTbitem _v;
            _v = global::moba_luban.DRResourceDemoTbitem.DeserializeDRResourceDemoTbitem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRResourceDemoTbitem> DataMap => _dataMap;
    public System.Collections.Generic.List<DRResourceDemoTbitem> DataList => _dataList;

    public DRResourceDemoTbitem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRResourceDemoTbitem Get(int key) => _dataMap[key];
    public DRResourceDemoTbitem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

