
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class ResourceBattleStart
{
    private readonly System.Collections.Generic.Dictionary<int, DRResourceBattleStart> _dataMap;
    private readonly System.Collections.Generic.List<DRResourceBattleStart> _dataList;
    
    public ResourceBattleStart(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRResourceBattleStart>(n);
        _dataList = new System.Collections.Generic.List<DRResourceBattleStart>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRResourceBattleStart _v;
            _v = global::moba_luban.DRResourceBattleStart.DeserializeDRResourceBattleStart(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RowId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRResourceBattleStart> DataMap => _dataMap;
    public System.Collections.Generic.List<DRResourceBattleStart> DataList => _dataList;

    public DRResourceBattleStart GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRResourceBattleStart Get(int key) => _dataMap[key];
    public DRResourceBattleStart this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

