
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class ResourceActorStateMachines
{
    private readonly System.Collections.Generic.Dictionary<int, DRResourceActorStateMachines> _dataMap;
    private readonly System.Collections.Generic.List<DRResourceActorStateMachines> _dataList;
    
    public ResourceActorStateMachines(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRResourceActorStateMachines>(n);
        _dataList = new System.Collections.Generic.List<DRResourceActorStateMachines>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRResourceActorStateMachines _v;
            _v = global::moba_luban.DRResourceActorStateMachines.DeserializeDRResourceActorStateMachines(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RowId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRResourceActorStateMachines> DataMap => _dataMap;
    public System.Collections.Generic.List<DRResourceActorStateMachines> DataList => _dataList;

    public DRResourceActorStateMachines GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRResourceActorStateMachines Get(int key) => _dataMap[key];
    public DRResourceActorStateMachines this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

