
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class SearchQueryTemplates
{
    private readonly System.Collections.Generic.Dictionary<int, DRSearchQueryTemplates> _dataMap;
    private readonly System.Collections.Generic.List<DRSearchQueryTemplates> _dataList;
    
    public SearchQueryTemplates(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRSearchQueryTemplates>(n);
        _dataList = new System.Collections.Generic.List<DRSearchQueryTemplates>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRSearchQueryTemplates _v;
            _v = global::moba_luban.DRSearchQueryTemplates.DeserializeDRSearchQueryTemplates(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRSearchQueryTemplates> DataMap => _dataMap;
    public System.Collections.Generic.List<DRSearchQueryTemplates> DataList => _dataList;

    public DRSearchQueryTemplates GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRSearchQueryTemplates Get(int key) => _dataMap[key];
    public DRSearchQueryTemplates this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

