
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class SkillFlows
{
    private readonly System.Collections.Generic.Dictionary<int, DRSkillFlows> _dataMap;
    private readonly System.Collections.Generic.List<DRSkillFlows> _dataList;
    
    public SkillFlows(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRSkillFlows>(n);
        _dataList = new System.Collections.Generic.List<DRSkillFlows>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRSkillFlows _v;
            _v = global::moba_luban.DRSkillFlows.DeserializeDRSkillFlows(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRSkillFlows> DataMap => _dataMap;
    public System.Collections.Generic.List<DRSkillFlows> DataList => _dataList;

    public DRSkillFlows GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRSkillFlows Get(int key) => _dataMap[key];
    public DRSkillFlows this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

