
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class SkillLevelTables
{
    private readonly System.Collections.Generic.Dictionary<int, DRSkillLevelTables> _dataMap;
    private readonly System.Collections.Generic.List<DRSkillLevelTables> _dataList;
    
    public SkillLevelTables(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRSkillLevelTables>(n);
        _dataList = new System.Collections.Generic.List<DRSkillLevelTables>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRSkillLevelTables _v;
            _v = global::moba_luban.DRSkillLevelTables.DeserializeDRSkillLevelTables(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRSkillLevelTables> DataMap => _dataMap;
    public System.Collections.Generic.List<DRSkillLevelTables> DataList => _dataList;

    public DRSkillLevelTables GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRSkillLevelTables Get(int key) => _dataMap[key];
    public DRSkillLevelTables this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

