
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class Skills
{
    private readonly System.Collections.Generic.Dictionary<int, DRSkills> _dataMap;
    private readonly System.Collections.Generic.List<DRSkills> _dataList;
    
    public Skills(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRSkills>(n);
        _dataList = new System.Collections.Generic.List<DRSkills>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRSkills _v;
            _v = global::moba_luban.DRSkills.DeserializeDRSkills(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRSkills> DataMap => _dataMap;
    public System.Collections.Generic.List<DRSkills> DataList => _dataList;

    public DRSkills GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRSkills Get(int key) => _dataMap[key];
    public DRSkills this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

