
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class SkillButtonTemplates
{
    private readonly System.Collections.Generic.Dictionary<int, DRSkillButtonTemplates> _dataMap;
    private readonly System.Collections.Generic.List<DRSkillButtonTemplates> _dataList;
    
    public SkillButtonTemplates(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRSkillButtonTemplates>(n);
        _dataList = new System.Collections.Generic.List<DRSkillButtonTemplates>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRSkillButtonTemplates _v;
            _v = global::moba_luban.DRSkillButtonTemplates.DeserializeDRSkillButtonTemplates(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRSkillButtonTemplates> DataMap => _dataMap;
    public System.Collections.Generic.List<DRSkillButtonTemplates> DataList => _dataList;

    public DRSkillButtonTemplates GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRSkillButtonTemplates Get(int key) => _dataMap[key];
    public DRSkillButtonTemplates this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

