
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class SpawnSummonActionTemplates
{
    private readonly System.Collections.Generic.Dictionary<int, DRSpawnSummonActionTemplates> _dataMap;
    private readonly System.Collections.Generic.List<DRSpawnSummonActionTemplates> _dataList;
    
    public SpawnSummonActionTemplates(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRSpawnSummonActionTemplates>(n);
        _dataList = new System.Collections.Generic.List<DRSpawnSummonActionTemplates>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRSpawnSummonActionTemplates _v;
            _v = global::moba_luban.DRSpawnSummonActionTemplates.DeserializeDRSpawnSummonActionTemplates(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRSpawnSummonActionTemplates> DataMap => _dataMap;
    public System.Collections.Generic.List<DRSpawnSummonActionTemplates> DataList => _dataList;

    public DRSpawnSummonActionTemplates GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRSpawnSummonActionTemplates Get(int key) => _dataMap[key];
    public DRSpawnSummonActionTemplates this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

