
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class Summons
{
    private readonly System.Collections.Generic.Dictionary<int, DRSummons> _dataMap;
    private readonly System.Collections.Generic.List<DRSummons> _dataList;
    
    public Summons(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DRSummons>(n);
        _dataList = new System.Collections.Generic.List<DRSummons>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRSummons _v;
            _v = global::moba_luban.DRSummons.DeserializeDRSummons(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DRSummons> DataMap => _dataMap;
    public System.Collections.Generic.List<DRSummons> DataList => _dataList;

    public DRSummons GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRSummons Get(int key) => _dataMap[key];
    public DRSummons this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

