
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace moba_luban
{
public partial class SummonAttrInherits
{
    private readonly System.Collections.Generic.Dictionary<string, DRSummonAttrInherits> _dataMap;
    private readonly System.Collections.Generic.List<DRSummonAttrInherits> _dataList;
    
    public SummonAttrInherits(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, DRSummonAttrInherits>(n);
        _dataList = new System.Collections.Generic.List<DRSummonAttrInherits>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DRSummonAttrInherits _v;
            _v = global::moba_luban.DRSummonAttrInherits.DeserializeDRSummonAttrInherits(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, DRSummonAttrInherits> DataMap => _dataMap;
    public System.Collections.Generic.List<DRSummonAttrInherits> DataList => _dataList;

    public DRSummonAttrInherits GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRSummonAttrInherits Get(string key) => _dataMap[key];
    public DRSummonAttrInherits this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

