
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace moba_luban
{
public partial class Tables
{
    public Characters Characters {get; }
    public AttributeTemplates AttributeTemplates {get; }
    public AttrTypes AttrTypes {get; }
    public Skills Skills {get; }
    public PassiveSkills PassiveSkills {get; }
    public SkillLevelTables SkillLevelTables {get; }
    public Models Models {get; }
    public Buffs Buffs {get; }
    public ContinuousProcesses ContinuousProcesses {get; }
    public ProjectileLaunchers ProjectileLaunchers {get; }
    public Projectiles Projectiles {get; }
    public Aoes Aoes {get; }
    public Emitters Emitters {get; }
    public Summons Summons {get; }
    public SummonAttrInherits SummonAttrInherits {get; }
    public ComponentTemplates ComponentTemplates {get; }
    public SkillButtonTemplates SkillButtonTemplates {get; }
    public TagTemplates TagTemplates {get; }
    public ContinuousTagTemplates ContinuousTagTemplates {get; }
    public SearchQueryTemplates SearchQueryTemplates {get; }
    public SpawnSummonActionTemplates SpawnSummonActionTemplates {get; }
    public PresentationTemplates PresentationTemplates {get; }
    public BattleMaps BattleMaps {get; }
    public Gameplays Gameplays {get; }
    public MotionGroups MotionGroups {get; }
    public Effects Effects {get; }
    public Brains Brains {get; }
    public ResourceActorStateMachines ResourceActorStateMachines {get; }
    public ResourceAttributetemplates ResourceAttributetemplates {get; }
    public ResourceBattleStart ResourceBattleStart {get; }
    public ResourceCharacterHfsm ResourceCharacterHfsm {get; }
    public ResourceCharacterViewActions ResourceCharacterViewActions {get; }
    public ResourceDemoTbitem ResourceDemoTbitem {get; }
    public ResourceDtbuff ResourceDtbuff {get; }
    public ResourceEffectPlans ResourceEffectPlans {get; }
    public ResourceOngoingEffects ResourceOngoingEffects {get; }
    public AbilityNodes AbilityNodes {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        Characters = new Characters(loader("characters"));
        AttributeTemplates = new AttributeTemplates(loader("attribute_templates"));
        AttrTypes = new AttrTypes(loader("attr_types"));
        Skills = new Skills(loader("skills"));
        PassiveSkills = new PassiveSkills(loader("passive_skills"));
        SkillLevelTables = new SkillLevelTables(loader("skill_level_tables"));
        Models = new Models(loader("models"));
        Buffs = new Buffs(loader("buffs"));
        ContinuousProcesses = new ContinuousProcesses(loader("continuous_processes"));
        ProjectileLaunchers = new ProjectileLaunchers(loader("projectile_launchers"));
        Projectiles = new Projectiles(loader("projectiles"));
        Aoes = new Aoes(loader("aoes"));
        Emitters = new Emitters(loader("emitters"));
        Summons = new Summons(loader("summons"));
        SummonAttrInherits = new SummonAttrInherits(loader("summon_attr_inherits"));
        ComponentTemplates = new ComponentTemplates(loader("component_templates"));
        SkillButtonTemplates = new SkillButtonTemplates(loader("skill_button_templates"));
        TagTemplates = new TagTemplates(loader("tag_templates"));
        ContinuousTagTemplates = new ContinuousTagTemplates(loader("continuous_tag_templates"));
        SearchQueryTemplates = new SearchQueryTemplates(loader("search_query_templates"));
        SpawnSummonActionTemplates = new SpawnSummonActionTemplates(loader("spawn_summon_action_templates"));
        PresentationTemplates = new PresentationTemplates(loader("presentation_templates"));
        BattleMaps = new BattleMaps(loader("battle_maps"));
        Gameplays = new Gameplays(loader("gameplays"));
        MotionGroups = new MotionGroups(loader("motion_groups"));
        Effects = new Effects(loader("effects"));
        Brains = new Brains(loader("brains"));
        ResourceActorStateMachines = new ResourceActorStateMachines(loader("actor_state_machines"));
        ResourceAttributetemplates = new ResourceAttributetemplates(loader("attributetemplates"));
        ResourceBattleStart = new ResourceBattleStart(loader("battle_start"));
        ResourceCharacterHfsm = new ResourceCharacterHfsm(loader("character_hfsm"));
        ResourceCharacterViewActions = new ResourceCharacterViewActions(loader("character_view_actions"));
        ResourceDemoTbitem = new ResourceDemoTbitem(loader("demo_tbitem"));
        ResourceDtbuff = new ResourceDtbuff(loader("dtbuff"));
        ResourceEffectPlans = new ResourceEffectPlans(loader("effect_plans"));
        ResourceOngoingEffects = new ResourceOngoingEffects(loader("ongoing_effects"));
        AbilityNodes = new AbilityNodes(loader("ability_nodes"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Characters.ResolveRef(this);
        AttributeTemplates.ResolveRef(this);
        AttrTypes.ResolveRef(this);
        Skills.ResolveRef(this);
        PassiveSkills.ResolveRef(this);
        SkillLevelTables.ResolveRef(this);
        Models.ResolveRef(this);
        Buffs.ResolveRef(this);
        ContinuousProcesses.ResolveRef(this);
        ProjectileLaunchers.ResolveRef(this);
        Projectiles.ResolveRef(this);
        Aoes.ResolveRef(this);
        Emitters.ResolveRef(this);
        Summons.ResolveRef(this);
        SummonAttrInherits.ResolveRef(this);
        ComponentTemplates.ResolveRef(this);
        SkillButtonTemplates.ResolveRef(this);
        TagTemplates.ResolveRef(this);
        ContinuousTagTemplates.ResolveRef(this);
        SearchQueryTemplates.ResolveRef(this);
        SpawnSummonActionTemplates.ResolveRef(this);
        PresentationTemplates.ResolveRef(this);
        BattleMaps.ResolveRef(this);
        Gameplays.ResolveRef(this);
        MotionGroups.ResolveRef(this);
        Effects.ResolveRef(this);
        Brains.ResolveRef(this);
        ResourceActorStateMachines.ResolveRef(this);
        ResourceAttributetemplates.ResolveRef(this);
        ResourceBattleStart.ResolveRef(this);
        ResourceCharacterHfsm.ResolveRef(this);
        ResourceCharacterViewActions.ResolveRef(this);
        ResourceDemoTbitem.ResolveRef(this);
        ResourceDtbuff.ResolveRef(this);
        ResourceEffectPlans.ResolveRef(this);
        ResourceOngoingEffects.ResolveRef(this);
        AbilityNodes.ResolveRef(this);
    }
}

}
