using System.Globalization;
using System.Text;
using AbilityKit.Protocol.CatalogCompiler.Ir;

namespace AbilityKit.Protocol.CatalogCompiler.Emit;

/// <summary>
/// Emits the <c>BuiltInProtocolCatalogs</c> C# source from the codec-neutral IR. The emitted
/// class materializes the runtime <c>ProtocolCatalogDefinition</c> array, so the codec name stays
/// an opaque string here rather than binding to a concrete codec backend.
/// </summary>
public static class CSharpEmitter
{
    public static string Emit(
        IReadOnlyList<ProtocolCatalogIr> catalogs,
        IReadOnlyList<string> sources,
        string targetNamespace,
        string className)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.Append("// Sources: ").AppendLine(string.Join(", ", sources));
        builder.AppendLine("using System;");
        builder.AppendLine("using AbilityKit.Protocol.Catalog;");
        builder.AppendLine();
        builder.Append("namespace ").AppendLine(targetNamespace);
        builder.AppendLine("{");
        builder.Append("    public static class ").AppendLine(className);
        builder.AppendLine("    {");
        builder.AppendLine("        private static readonly ProtocolCatalogDefinition[] Catalogs =");
        builder.AppendLine("        {");
        foreach (var catalog in catalogs)
        {
            builder.AppendLine("            new ProtocolCatalogDefinition(");
            builder.Append("                ").Append(Literal(catalog.CatalogId)).AppendLine(",");
            builder.Append("                ").Append(Literal(catalog.ProjectId)).AppendLine(",");
            builder.Append("                ").Append(Literal(catalog.Domain)).AppendLine(",");
            builder.Append("                ").Append(catalog.Revision.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
            builder.Append("                ").Append(Literal(catalog.DefaultCodec)).AppendLine(",");
            builder.AppendLine("                new ProtocolMessageDefinition[]");
            builder.AppendLine("                {");
            foreach (var message in catalog.Messages)
            {
                builder.AppendLine("                    new ProtocolMessageDefinition(");
                builder.Append("                        ").Append(Literal(message.Id)).AppendLine(",");
                builder.Append("                        ").Append(message.OpCode.ToString(CultureInfo.InvariantCulture)).AppendLine("u,");
                builder.Append("                        ProtocolDirection.").Append(message.Direction).AppendLine(",");
                builder.Append("                        ProtocolPacketKind.").Append(message.Kind).AppendLine(",");
                builder.Append("                        ").Append(Literal(message.PayloadType)).AppendLine(",");
                builder.Append("                        ").Append(Literal(message.Codec)).AppendLine(",");
                builder.Append("                        ProtocolReliability.").Append(message.Reliability).AppendLine(",");
                builder.Append("                        ").Append(LiteralOrNull(message.ResponseId)).AppendLine(",");
                builder.Append("                        ").Append(message.MinimumSchemaVersion.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
                builder.Append("                        ").Append(message.MaximumSchemaVersion.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
                builder.Append("                        ").Append(message.MaximumPayloadBytes.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
                builder.Append("                        ").Append(message.CaptureSampleRate.ToString("R", CultureInfo.InvariantCulture)).AppendLine("d,");
                AppendSensitiveFields(builder, message.SensitiveFields);
                builder.AppendLine("                    ),");
            }
            builder.AppendLine("                }),");
        }
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        public static System.Collections.Generic.IReadOnlyList<ProtocolCatalogDefinition> All => Catalogs;");
        builder.AppendLine();
        builder.AppendLine("        public static ProtocolCatalogRegistry CreateRegistry()");
        builder.AppendLine("        {");
        builder.AppendLine("            var registry = new ProtocolCatalogRegistry();");
        builder.AppendLine("            for (var i = 0; i < Catalogs.Length; i++) registry.Register(Catalogs[i]);");
        builder.AppendLine("            return registry;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendSensitiveFields(StringBuilder builder, IReadOnlyList<string> fields)
    {
        if (fields.Count == 0)
        {
            builder.AppendLine("                        null");
            return;
        }

        builder.Append("                        new[] { ");
        for (var i = 0; i < fields.Count; i++)
        {
            if (i > 0) builder.Append(", ");
            builder.Append(Literal(fields[i]));
        }
        builder.AppendLine(" }");
    }

    private static string LiteralOrNull(string value) =>
        string.IsNullOrEmpty(value) ? "null" : Literal(value);

    private static string Literal(string value) =>
        "\"" + (value ?? string.Empty).Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";
}
