using System.Text;
using AbilityKit.Protocol.CatalogCompiler.Ir;

namespace AbilityKit.Protocol.CatalogCompiler.Emit;

/// <summary>
/// Emits the MemoryPack backend surface for a single project export: a codec facade that wraps
/// <c>MemoryPackSerializer</c> behind typed helpers, plus decoder-registration glue that wires each
/// memorypack catalog message owning a generated wire schema into
/// <c>ProtocolPayloadDecoderRegistry</c>. The emitted file references <c>MemoryPack</c> and therefore
/// lives in the opt-in project export folder, never in the always-compiled built-in catalog.
/// </summary>
public static class MemoryPackBackendEmitter
{
    public static string Emit(
        IReadOnlyList<ProtocolCatalogIr> catalogs,
        IReadOnlyList<WireSchemaIr> schemas,
        string targetNamespace)
    {
        ArgumentNullException.ThrowIfNull(catalogs);
        ArgumentNullException.ThrowIfNull(schemas);
        if (string.IsNullOrWhiteSpace(targetNamespace))
            throw new InvalidDataException("A target namespace is required for the MemoryPack backend.");

        var ownedTypes = new HashSet<string>(
            schemas.Select(MemoryPackExportPlanner.QualifiedType),
            StringComparer.Ordinal);

        var registrations = new List<Registration>();
        foreach (var catalog in catalogs)
        {
            foreach (var message in catalog.Messages)
            {
                if (!string.Equals(message.Codec, "memorypack", StringComparison.OrdinalIgnoreCase))
                    continue;
                var elementType = MemoryPackExportPlanner.ElementType(message.PayloadType);
                if (!ownedTypes.Contains(elementType))
                    continue;
                registrations.Add(new Registration(catalog.CatalogId, message.Id, elementType));
            }
        }

        var projectId = catalogs.Count > 0 ? catalogs[0].ProjectId : string.Empty;
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.Append("// Project: ").AppendLine(projectId);
        builder.AppendLine("using System;");
        builder.AppendLine("using MemoryPack;");
        builder.AppendLine("using AbilityKit.Protocol.Catalog;");
        builder.AppendLine();
        builder.Append("namespace ").AppendLine(targetNamespace);
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>MemoryPack codec facade and decoder registration for this project export.</summary>");
        builder.AppendLine("    public static class ProjectMemoryPackCodecs");
        builder.AppendLine("    {");
        builder.AppendLine("        public static byte[] Serialize<T>(in T value) => MemoryPackSerializer.Serialize(value);");
        builder.AppendLine();
        builder.AppendLine("        public static T Deserialize<T>(byte[] bytes) => MemoryPackSerializer.Deserialize<T>(bytes);");
        builder.AppendLine();
        builder.AppendLine("        public static T Deserialize<T>(ReadOnlySpan<byte> bytes) => MemoryPackSerializer.Deserialize<T>(bytes);");
        builder.AppendLine();
        builder.AppendLine("        public static void Register(ProtocolPayloadDecoderRegistry registry)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (registry == null) throw new ArgumentNullException(nameof(registry));");
        builder.AppendLine();
        foreach (var registration in registrations)
        {
            builder.Append("            registry.TryRegister(")
                .Append(Literal(registration.CatalogId))
                .Append(", ")
                .Append(Literal(registration.MessageId))
                .Append(", Decode<")
                .Append(registration.Type)
                .AppendLine(">);");
        }

        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static object? Decode<T>(ArraySegment<byte> payload)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (payload.Array == null || payload.Count == 0) return default(T);");
        builder.AppendLine("            return MemoryPackSerializer.Deserialize<T>(");
        builder.AppendLine("                new ReadOnlySpan<byte>(payload.Array, payload.Offset, payload.Count));");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>
    /// Resolves the unique memorypack catalog message whose payload element type equals a schema's
    /// qualified type. Returns <c>null</c> when no message references the type or when more than one
    /// does, since a single <c>ProtocolOpCode</c> cannot represent an ambiguous opcode mapping.
    /// </summary>
    public static ProtocolMessageIr? ResolveProtocolMessage(
        WireSchemaIr schema,
        IReadOnlyList<ProtocolCatalogIr> catalogs)
    {
        ArgumentNullException.ThrowIfNull(schema);
        ArgumentNullException.ThrowIfNull(catalogs);
        var qualifiedType = MemoryPackExportPlanner.QualifiedType(schema);

        ProtocolMessageIr? match = null;
        foreach (var catalog in catalogs)
        {
            foreach (var message in catalog.Messages)
            {
                if (!string.Equals(message.Codec, "memorypack", StringComparison.OrdinalIgnoreCase))
                    continue;
                if (!string.Equals(
                        MemoryPackExportPlanner.ElementType(message.PayloadType),
                        qualifiedType,
                        StringComparison.Ordinal))
                    continue;

                if (match != null) return null;
                match = message;
            }
        }

        return match;
    }

    private static string Literal(string value) =>
        "\"" + (value ?? string.Empty).Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    private sealed record Registration(string CatalogId, string MessageId, string Type);
}
