using System.Globalization;
using System.Text;
using AbilityKit.Protocol.CatalogCompiler.Ir;

namespace AbilityKit.Protocol.CatalogCompiler.Emit;

/// <summary>Emits MemoryPack DTOs from field-level wire schemas.</summary>
public static class MemoryPackWireEmitter
{
    public static string Emit(WireSchemaIr schema) => Emit(schema, null);

    /// <summary>
    /// Emits the MemoryPack DTO, optionally annotated with <c>ProtocolOpCode</c> when the schema's
    /// qualified type maps to exactly one catalog message. The overload without a message keeps the
    /// codec-neutral declaration shape used by schema-only tests and previews.
    /// </summary>
    public static string Emit(WireSchemaIr schema, ProtocolMessageIr? protocolMessage)
    {
        ArgumentNullException.ThrowIfNull(schema);
        if (string.IsNullOrWhiteSpace(schema.ProjectId) || string.IsNullOrWhiteSpace(schema.TargetNamespace))
            throw new InvalidDataException(
                $"Wire schema '{schema.Type}' must declare projectId and namespace before export.");
        ValidateIdentifier(schema.Type, "type");
        ValidateNamespace(schema.TargetNamespace);
        var propertyNames = new HashSet<string>(StringComparer.Ordinal);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.Append("// Project: ").AppendLine(schema.ProjectId);
        builder.AppendLine("using System;");
        builder.AppendLine("using MemoryPack;");
        if (protocolMessage != null) builder.AppendLine("using AbilityKit.Protocol;");
        builder.AppendLine();
        builder.Append("namespace ").AppendLine(schema.TargetNamespace);
        builder.AppendLine("{");
        if (protocolMessage != null) AppendProtocolAttribute(builder, schema, protocolMessage);
        builder.AppendLine(schema.MemoryPackMode == WireMemoryPackMode.VersionTolerant
            ? "    [MemoryPackable(GenerateType.VersionTolerant)]"
            : "    [MemoryPackable]");
        builder.Append("    public partial ")
            .Append(schema.DeclarationKind == WireDeclarationKind.Struct ? "struct " : "class ")
            .AppendLine(schema.Type);
        builder.AppendLine("    {");
        foreach (var field in schema.Fields.OrderBy(value => value.Id))
        {
            if (field.Id > int.MaxValue)
                throw new InvalidDataException($"Field '{field.Name}' id exceeds MemoryPackOrder range.");
            ValidateIdentifier(field.Name, "field");
            var typeName = ResolveType(field);
            var propertyName = ToPascalCase(field.Name);
            if (!propertyNames.Add(propertyName))
                throw new InvalidDataException($"Wire fields generate duplicate property '{propertyName}'.");
            builder.Append("        [MemoryPackOrder(")
                .Append(field.Id.ToString(CultureInfo.InvariantCulture))
                .AppendLine(")]");
            builder.Append("        public ").Append(typeName).Append(' ').Append(propertyName);
            if (schema.MemberStyle == WireMemberStyle.Property) builder.Append(" { get; set; }");
            var initializer = schema.DeclarationKind == WireDeclarationKind.Struct
                ? string.Empty
                : Initializer(field);
            if (initializer.Length > 0) builder.Append(" = ").Append(initializer).Append(';');
            else if (schema.MemberStyle == WireMemberStyle.Field) builder.Append(';');
            builder.AppendLine();
            builder.AppendLine();
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string ResolveType(WireFieldIr field)
    {
        var scalar = field.IsCustomType ? ResolveCustomType(field.TypeName) : field.ScalarType switch
        {
            "bool" => "bool",
            "uint8" => "byte",
            "int32" => "int",
            "int64" => "long",
            "uint32" => "uint",
            "uint64" => "ulong",
            "float" => "float",
            "double" => "double",
            "string" => "string",
            "bytes" => "byte[]",
            _ => throw new InvalidDataException($"Unsupported scalar type '{field.ScalarType}'.")
        };
        if (field.IsArray && field.ScalarType != "bytes") scalar += "[]";
        if (!field.IsOptional) return scalar;
        if (scalar is "string" || scalar.EndsWith("[]", StringComparison.Ordinal)) return scalar + "?";
        return scalar + "?";
    }

    private static string Initializer(WireFieldIr field)
    {
        if (field.IsOptional) return string.Empty;
        if (field.IsCustomType && !field.IsArray) return "default!";
        if (field.ScalarType == "string") return "string.Empty";
        if (field.ScalarType == "bytes") return "Array.Empty<byte>()";
        if (field.IsArray)
        {
            var element = field.IsCustomType
                ? ResolveCustomType(field.TypeName)
                : ResolveType(new WireFieldIr(field.Id, field.Name, field.ScalarType, false, false));
            return $"Array.Empty<{element}>()";
        }
        return string.Empty;
    }

    private static string ResolveCustomType(string value)
    {
        ValidateQualifiedIdentifier(value, "type reference");
        return value;
    }

    private static string ToPascalCase(string value) =>
        value.Length == 0 ? value : char.ToUpperInvariant(value[0]) + value.Substring(1);

    private static void AppendProtocolAttribute(
        StringBuilder builder,
        WireSchemaIr schema,
        ProtocolMessageIr message)
    {
        builder.Append("    [ProtocolOpCode(")
            .Append(message.OpCode.ToString(CultureInfo.InvariantCulture))
            .Append("u, ProtocolDirection.")
            .Append(FormatDirection(message.Direction))
            .Append(", nameof(")
            .Append(schema.Type)
            .AppendLine("))]");
    }

    private static string FormatDirection(IrDirection direction) => direction switch
    {
        IrDirection.ClientToServer => "ClientToServer",
        IrDirection.ServerToClient => "ServerToClient",
        _ => "Bidirectional"
    };

    private static void ValidateIdentifier(string value, string kind)
    {
        if (string.IsNullOrWhiteSpace(value) || !(char.IsLetter(value[0]) || value[0] == '_') ||
            value.Skip(1).Any(ch => !(char.IsLetterOrDigit(ch) || ch == '_')))
            throw new InvalidDataException($"Wire {kind} '{value}' is not a valid C# identifier.");
    }

    private static void ValidateNamespace(string value)
    {
        ValidateQualifiedIdentifier(value, "namespace");
    }

    private static void ValidateQualifiedIdentifier(string value, string kind)
    {
        var parts = value.Split('.');
        if (parts.Length == 0 || parts.Any(part => string.IsNullOrWhiteSpace(part) ||
            !(char.IsLetter(part[0]) || part[0] == '_') ||
            part.Skip(1).Any(ch => !(char.IsLetterOrDigit(ch) || ch == '_'))))
            throw new InvalidDataException($"Wire {kind} '{value}' is not a valid C# name.");
    }
}
