using System.Globalization;
using System.Text;
using AbilityKit.Protocol.CatalogCompiler.Ir;

namespace AbilityKit.Protocol.CatalogCompiler.Emit;

/// <summary>
/// Emits an independent static metadata surface. This deliberately does not alter
/// <see cref="CSharpEmitter"/> or the BuiltInProtocolCatalogs golden output.
/// </summary>
public static class ProtocolMetadataEmitter
{
    public static string Emit(
        IReadOnlyList<ProtocolCatalogIr> catalogs,
        IReadOnlyList<string> sources,
        string targetNamespace,
        string className)
    {
        if (catalogs == null) throw new ArgumentNullException(nameof(catalogs));
        if (sources == null) throw new ArgumentNullException(nameof(sources));
        var entries = catalogs.SelectMany((catalog, catalogIndex) => catalog.Messages.Select(message =>
            (catalog, message, source: catalogIndex < sources.Count ? sources[catalogIndex] : string.Empty))).ToArray();
        var opcodeNames = BuildOpcodeNames(entries);
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.Append("// Sources: ").AppendLine(string.Join(", ", sources));
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using AbilityKit.Protocol;");
        builder.AppendLine("using AbilityKit.Protocol.Catalog;");
        builder.AppendLine();
        builder.Append("namespace ").AppendLine(targetNamespace);
        builder.AppendLine("{");
        builder.Append("    public static class ").AppendLine(className);
        builder.AppendLine("    {");
        builder.AppendLine("        public const int SchemaVersion = 1;");
        builder.AppendLine("        public static readonly ProtocolMessageMetadata[] Messages =");
        builder.AppendLine("        {");
        foreach (var entry in entries)
        {
            var message = entry.message;
            builder.AppendLine("            new ProtocolMessageMetadata(");
            builder.Append("                ").Append(Literal(entry.catalog.CatalogId)).AppendLine(",");
            builder.Append("                ").Append(Literal(message.Id)).AppendLine(",");
            builder.Append("                ").Append(message.OpCode.ToString(CultureInfo.InvariantCulture)).AppendLine("u,");
            builder.Append("                ProtocolDirection.").Append(message.Direction).AppendLine(",");
            builder.Append("                ProtocolPacketKind.").Append(message.Kind).AppendLine(",");
            builder.Append("                ").Append(Literal(message.PayloadType)).AppendLine(",");
            builder.Append("                ").Append(Literal(message.Codec)).AppendLine(",");
            builder.Append("                ProtocolReliability.").Append(message.Reliability).AppendLine(",");
            builder.Append("                ").Append(LiteralOrNull(message.ResponseId)).AppendLine(",");
            builder.Append("                ").Append(Literal(entry.source)).AppendLine(",");
            builder.Append("                ").Append(message.MinimumSchemaVersion.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
            builder.Append("                ").Append(message.MaximumSchemaVersion.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
            builder.Append("                ").Append(message.MaximumPayloadBytes.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
            builder.Append("                ").Append(message.CaptureSampleRate.ToString("R", CultureInfo.InvariantCulture)).AppendLine("d,");
            if (message.SensitiveFields.Count == 0)
                builder.AppendLine("                null),");
            else
            {
                builder.Append("                new[] { ");
                for (var i = 0; i < message.SensitiveFields.Count; i++)
                {
                    if (i > 0) builder.Append(", ");
                    builder.Append(Literal(message.SensitiveFields[i]));
                }
                builder.AppendLine(" }),");
            }
        }
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        public static class Opcodes");
        builder.AppendLine("        {");
        foreach (var entry in entries)
            builder.Append("            public const uint ").Append(opcodeNames[(entry.message.Id, entry.catalog.CatalogId)]).Append(" = ").Append(entry.message.OpCode.ToString(CultureInfo.InvariantCulture)).AppendLine("u;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static readonly IReadOnlyDictionary<string, string> SourceMap =");
        builder.AppendLine("            new Dictionary<string, string>");
        builder.AppendLine("            {");
        foreach (var entry in entries)
            builder.Append("                [").Append(Literal(entry.catalog.CatalogId + "/" + entry.message.Id)).Append("] = ").Append(Literal(entry.source)).AppendLine(",");
        builder.AppendLine("            };");
        builder.AppendLine();
        builder.AppendLine("        public static ProtocolMetadataRegistry CreateRegistry() => ProtocolStaticRegistry.Create(Messages);");
        builder.AppendLine("        public static ProtocolMetadataRegistry CreateRegistry(ProtocolCatalogRegistry catalogs) => ProtocolStaticRegistry.Create(catalogs, SourceMap);");
        builder.AppendLine("        public static void Register(ProtocolMetadataRegistry registry) => ProtocolStaticRegistry.RegisterAll(registry, Messages);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static Dictionary<(string Id, string Catalog), string> BuildOpcodeNames(
        IReadOnlyList<(ProtocolCatalogIr catalog, ProtocolMessageIr message, string source)> entries)
    {
        var result = new Dictionary<(string, string), string>();
        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var entry in entries)
        {
            var baseName = ToIdentifier(entry.catalog.CatalogId + "_" + entry.message.Id);
            var name = baseName;
            var suffix = 2;
            while (!used.Add(name)) name = baseName + "_" + suffix++.ToString(CultureInfo.InvariantCulture);
            result[(entry.message.Id, entry.catalog.CatalogId)] = name;
        }

        return result;
    }

    private static string ToIdentifier(string value)
    {
        var builder = new StringBuilder();
        foreach (var ch in value)
            builder.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        if (builder.Length == 0 || char.IsDigit(builder[0])) builder.Insert(0, '_');
        return builder.ToString();
    }

    private static string LiteralOrNull(string value) => string.IsNullOrEmpty(value) ? "null" : Literal(value);

    private static string Literal(string value) =>
        "\"" + (value ?? string.Empty).Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";
}
