using System.Globalization;
using System.Text;
using AbilityKit.Protocol.CatalogCompiler.Ir;

namespace AbilityKit.Protocol.CatalogCompiler.Emit;

/// <summary>Deterministically emits proto3 messages from codec-neutral wire schemas.</summary>
public sealed class ProtobufProtocolBackend : IProtocolBackend
{
    public string Codec => "protobuf";

    public ProtocolBackendCapabilities Capabilities =>
        ProtocolBackendCapabilities.StableFieldIds |
        ProtocolBackendCapabilities.ReservedFieldIds |
        ProtocolBackendCapabilities.OptionalFields |
        ProtocolBackendCapabilities.RepeatedFields |
        ProtocolBackendCapabilities.CustomTypes;

    public IReadOnlyList<ProtocolBackendOutput> EmitSchema(ProtocolBackendSchemaContext context)
    {
        ArgumentNullException.ThrowIfNull(context);
        var schema = context.Schema;
        ValidateIdentifier(schema.Type, "message");
        if (string.IsNullOrWhiteSpace(schema.ProjectId) || string.IsNullOrWhiteSpace(schema.TargetNamespace))
            throw new InvalidDataException(
                $"Wire schema '{schema.Type}' must declare projectId and namespace before export.");

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("syntax = \"proto3\";");
        builder.AppendLine();
        builder.Append("// Project: ").AppendLine(schema.ProjectId);
        builder.Append("package ").Append(ToProtoPackage(schema.TargetNamespace)).AppendLine(";");
        builder.AppendLine();
        builder.Append("message ").Append(schema.Type).AppendLine(" {");

        var reservedIds = schema.ReservedIds.OrderBy(value => value).ToArray();
        ValidateIds(schema, reservedIds);
        if (reservedIds.Length > 0)
        {
            builder.Append("  reserved ")
                .Append(string.Join(", ", reservedIds.Select(ProtoFieldNumber)))
                .AppendLine(";");
            builder.AppendLine();
        }

        foreach (var field in schema.Fields.OrderBy(value => value.Id))
        {
            ValidateIdentifier(field.Name, "field");
            var cardinality = field.IsArray && field.ScalarType != "bytes"
                ? "repeated "
                : field.IsOptional
                    ? "optional "
                    : string.Empty;
            builder.Append("  ")
                .Append(cardinality)
                .Append(ResolveType(field))
                .Append(' ')
                .Append(field.Name)
                .Append(" = ")
                .Append(ProtoFieldNumber(field.Id))
                .AppendLine(";");
        }

        builder.AppendLine("}");
        return new[] { new ProtocolBackendOutput(schema.Type + ".proto", builder.ToString()) };
    }

    private static string ResolveType(WireFieldIr field)
    {
        if (field.IsCustomType)
        {
            ValidateQualifiedIdentifier(field.TypeName, "type reference");
            return field.TypeName;
        }

        return field.ScalarType switch
        {
            "bool" => "bool",
            "int32" => "int32",
            "int64" => "int64",
            "uint32" => "uint32",
            "uint64" => "uint64",
            "float" => "float",
            "double" => "double",
            "string" => "string",
            "bytes" => "bytes",
            _ => throw new InvalidDataException($"Unsupported scalar type '{field.ScalarType}'.")
        };
    }

    private static void ValidateIds(WireSchemaIr schema, IReadOnlyCollection<uint> reservedIds)
    {
        var used = new HashSet<uint>();
        foreach (var field in schema.Fields)
        {
            ValidateFieldNumber(field.Id, $"Field '{field.Name}'");
            if (!used.Add(field.Id))
                throw new InvalidDataException($"Wire schema '{schema.Type}' contains duplicate field id {field.Id}.");
            if (reservedIds.Contains(field.Id))
                throw new InvalidDataException($"Field '{field.Name}' uses reserved id {field.Id}.");
        }

        foreach (var id in reservedIds) ValidateFieldNumber(id, "Reserved id");
    }

    private static string ProtoFieldNumber(uint zeroBasedId)
    {
        ValidateFieldNumber(zeroBasedId, "Wire field id");
        return (zeroBasedId + 1u).ToString(CultureInfo.InvariantCulture);
    }

    private static void ValidateFieldNumber(uint zeroBasedId, string owner)
    {
        // Wire IDs are zero-based; protobuf field numbers are one-based and exclude 19000-19999.
        if (zeroBasedId >= 536_870_911u)
            throw new InvalidDataException($"{owner} {zeroBasedId} exceeds the protobuf field-number range.");
        var fieldNumber = zeroBasedId + 1u;
        if (fieldNumber is >= 19_000u and <= 19_999u)
            throw new InvalidDataException($"{owner} {zeroBasedId} maps into protobuf's reserved field-number range.");
    }

    private static string ToProtoPackage(string value)
    {
        ValidateQualifiedIdentifier(value, "namespace");
        return string.Join('.', value.Split('.').Select(part => part.ToLowerInvariant()));
    }

    private static void ValidateIdentifier(string value, string kind)
    {
        if (string.IsNullOrWhiteSpace(value) || !(char.IsLetter(value[0]) || value[0] == '_') ||
            value.Skip(1).Any(ch => !(char.IsLetterOrDigit(ch) || ch == '_')))
            throw new InvalidDataException($"Wire {kind} '{value}' is not a valid protobuf identifier.");
    }

    private static void ValidateQualifiedIdentifier(string value, string kind)
    {
        var parts = value.Split('.');
        if (parts.Length == 0 || parts.Any(part => string.IsNullOrWhiteSpace(part) ||
            !(char.IsLetter(part[0]) || part[0] == '_') ||
            part.Skip(1).Any(ch => !(char.IsLetterOrDigit(ch) || ch == '_'))))
            throw new InvalidDataException($"Wire {kind} '{value}' is not a valid protobuf name.");
    }
}
