using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AbilityKit.Demo.Moba.CodeGen
{
    [Generator]
    public sealed class MobaProjectileEmitterManifestGenerator : ISourceGenerator
    {
        private const string ManifestMetadataName =
            "AbilityKit.Demo.Moba.Services.Projectile.Launch.MobaGeneratedProjectileEmitterManifest";

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new ProjectileEmitterSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is ProjectileEmitterSyntaxReceiver receiver)) return;

            var attributeType = context.Compilation.GetTypeByMetadataName(
                MobaProjectileEmitterContract.AttributeMetadataName);
            var interfaceType = context.Compilation.GetTypeByMetadataName(
                MobaProjectileEmitterContract.InterfaceMetadataName);
            var emitterType = context.Compilation.GetTypeByMetadataName(
                MobaProjectileEmitterContract.EmitterTypeMetadataName);
            var manifestType = context.Compilation.GetTypeByMetadataName(ManifestMetadataName);
            if (attributeType == null || interfaceType == null || emitterType == null || manifestType == null ||
                !manifestType.Locations.Any(location => location.IsInSource)) return;

            var mappings = new List<MobaProjectileEmitterMapping>();
            var seenTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var type in receiver.Types)
            {
                if (!seenTypes.Add(type)) continue;

                foreach (var attribute in type.GetAttributes().Where(candidate =>
                             SymbolEqualityComparer.Default.Equals(candidate.AttributeClass, attributeType)))
                {
                    if (!MobaProjectileEmitterContract.TryCreateMapping(
                            type,
                            interfaceType,
                            attribute,
                            out var mapping,
                            out _))
                    {
                        continue;
                    }

                    mappings.Add(mapping);
                }
            }

            var validMappings = new List<MobaProjectileEmitterMapping>();
            foreach (var group in mappings.GroupBy(
                         MobaProjectileEmitterContract.GetAmbiguityKey,
                         StringComparer.Ordinal))
            {
                var entries = group.OrderBy(item => item.QualifiedTypeName, StringComparer.Ordinal).ToArray();
                if (entries.Length > 1)
                {
                    continue;
                }

                validMappings.Add(entries[0]);
            }

            validMappings.Sort(CompareMappings);
            var hasAmbiguousDefaults = validMappings
                .Where(mapping => mapping.IsDefault)
                .Select(mapping => mapping.EmitterValue)
                .Distinct()
                .Skip(1)
                .Any();
            context.AddSource(
                "MobaGeneratedProjectileEmitterManifest.g.cs",
                GenerateSource(validMappings, emitterType, hasAmbiguousDefaults));
        }

        private static int CompareMappings(
            MobaProjectileEmitterMapping left,
            MobaProjectileEmitterMapping right)
        {
            var emitter = left.EmitterValue.CompareTo(right.EmitterValue);
            if (emitter != 0) return emitter;
            var priority = left.Priority.CompareTo(right.Priority);
            if (priority != 0) return priority;
            return string.CompareOrdinal(left.QualifiedTypeName, right.QualifiedTypeName);
        }

        private static string GenerateSource(
            IReadOnlyList<MobaProjectileEmitterMapping> mappings,
            INamedTypeSymbol emitterType,
            bool suppressDefaults)
        {
            var emitterTypeName = emitterType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace AbilityKit.Demo.Moba.Services.Projectile.Launch");
            source.AppendLine("{");
            source.AppendLine("    internal static partial class MobaGeneratedProjectileEmitterManifest");
            source.AppendLine("    {");
            source.AppendLine("        static partial void AddGenerated(MobaProjectileEmitterRegistry registry, ref int count)");
            source.AppendLine("        {");
            foreach (var mapping in mappings)
            {
                source.Append("            if (registry.TryRegister((")
                    .Append(emitterTypeName).Append(')').Append(mapping.EmitterValue)
                    .Append(", () => new ").Append(mapping.QualifiedTypeName).Append("(), ")
                    .Append(mapping.Priority).Append(", ")
                    .Append(mapping.IsDefault && !suppressDefaults ? "true" : "false").AppendLine(")) count++;");
            }

            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

    }

    internal sealed class ProjectileEmitterSyntaxReceiver : ISyntaxContextReceiver
    {
        public List<INamedTypeSymbol> Types { get; } = new List<INamedTypeSymbol>();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            if (context.Node is ClassDeclarationSyntax declaration && declaration.AttributeLists.Count > 0 &&
                context.SemanticModel.GetDeclaredSymbol(declaration) is INamedTypeSymbol type)
            {
                Types.Add(type);
            }
        }
    }
}
