using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AbilityKit.Demo.Moba.CodeGen
{
    [Generator]
    public sealed class MobaEventMappingManifestGenerator : ISourceGenerator
    {
        private const string ManifestMetadataName =
            "AbilityKit.Demo.Moba.Systems.MobaGeneratedEventMappingManifest";

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new EventMappingSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is EventMappingSyntaxReceiver receiver))
            {
                return;
            }

            var attributeType = context.Compilation.GetTypeByMetadataName(
                MobaEventMappingContract.AttributeMetadataName);
            var manifestType = context.Compilation.GetTypeByMetadataName(ManifestMetadataName);
            if (attributeType == null || manifestType == null ||
                !manifestType.Locations.Any(location => location.IsInSource))
            {
                return;
            }

            var mappings = new List<MobaEventMapping>();
            var seenTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var type in receiver.Types)
            {
                if (!seenTypes.Add(type))
                {
                    continue;
                }

                foreach (var attribute in type.GetAttributes().Where(candidate =>
                             SymbolEqualityComparer.Default.Equals(candidate.AttributeClass, attributeType)))
                {
                    if (!MobaEventMappingContract.TryCreateMapping(type, attribute, out var mapping, out _))
                    {
                        continue;
                    }

                    mappings.Add(mapping);
                }
            }

            var duplicateKeys = new HashSet<string>(
                mappings
                    .GroupBy(MobaEventMappingContract.GetDuplicateKey, StringComparer.Ordinal)
                    .Where(group => group.Count() > 1)
                    .Select(group => group.Key),
                StringComparer.Ordinal);
            if (duplicateKeys.Count > 0)
            {
                mappings.RemoveAll(mapping => duplicateKeys.Contains(
                    MobaEventMappingContract.GetDuplicateKey(mapping)));
            }

            mappings.Sort(CompareMappings);
            context.AddSource("MobaGeneratedEventMappingManifest.g.cs", GenerateSource(mappings));
        }

        private static int CompareMappings(MobaEventMapping left, MobaEventMapping right)
        {
            if (left.IsPrefix != right.IsPrefix)
            {
                return left.IsPrefix ? 1 : -1;
            }

            if (left.IsPrefix)
            {
                var length = right.EventId.Length.CompareTo(left.EventId.Length);
                if (length != 0)
                {
                    return length;
                }
            }

            return string.CompareOrdinal(left.EventId, right.EventId);
        }

        private static string GenerateSource(IReadOnlyList<MobaEventMapping> mappings)
        {
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace AbilityKit.Demo.Moba.Systems");
            source.AppendLine("{");
            source.AppendLine("    internal static partial class MobaGeneratedEventMappingManifest");
            source.AppendLine("    {");
            source.AppendLine("        static partial void AddGenerated(MobaEventSubscriptionRegistry registry, ref int count)");
            source.AppendLine("        {");
            foreach (var mapping in mappings)
            {
                source.Append(mapping.IsPrefix ? "            AddPrefix<" : "            AddExact<")
                    .Append(mapping.ArgsType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                    .Append(">(registry, ")
                    .Append(SymbolDisplay.FormatLiteral(mapping.EventId, true))
                    .AppendLine(", ref count);");
            }

            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

    }

    internal sealed class EventMappingSyntaxReceiver : ISyntaxContextReceiver
    {
        public List<INamedTypeSymbol> Types { get; } = new List<INamedTypeSymbol>();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            if (context.Node is TypeDeclarationSyntax declaration && declaration.AttributeLists.Count > 0 &&
                context.SemanticModel.GetDeclaredSymbol(declaration) is INamedTypeSymbol type)
            {
                Types.Add(type);
            }
        }
    }
}
