using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AbilityKit.Demo.Moba.CodeGen
{
    [Generator]
    public sealed class MobaBootstrapStageManifestGenerator : ISourceGenerator
    {
        private const string AttributeMetadataName =
            "AbilityKit.Demo.Moba.Systems.Bootstrap.Flow.MobaBootstrapStageAttribute";
        private const string BaseTypeMetadataName =
            "AbilityKit.Demo.Moba.Systems.Bootstrap.Flow.MobaBootstrapStageBase";
        private const string ManifestMetadataName =
            "AbilityKit.Demo.Moba.Systems.Bootstrap.Flow.MobaGeneratedBootstrapStageManifest";

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new BootstrapStageSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is BootstrapStageSyntaxReceiver receiver)) return;

            var attributeType = context.Compilation.GetTypeByMetadataName(AttributeMetadataName);
            var baseType = context.Compilation.GetTypeByMetadataName(BaseTypeMetadataName);
            var manifestType = context.Compilation.GetTypeByMetadataName(ManifestMetadataName);
            if (attributeType == null || baseType == null || manifestType == null ||
                !manifestType.Locations.Any(location => location.IsInSource)) return;

            var stages = new List<StageMapping>();
            var seenTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var type in receiver.Types)
            {
                if (!seenTypes.Add(type) || !type.GetAttributes().Any(candidate =>
                        SymbolEqualityComparer.Default.Equals(candidate.AttributeClass, attributeType)))
                {
                    continue;
                }

                if (!MobaBootstrapStageContract.TryValidate(type, baseType, out _))
                {
                    continue;
                }

                stages.Add(new StageMapping(
                    type,
                    MobaBootstrapStageContract.TryResolveStageName(type, context.Compilation)));
            }

            var duplicateTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var group in stages.Where(stage => stage.StageName != null)
                         .GroupBy(stage => stage.StageName!, StringComparer.Ordinal))
            {
                var entries = group.OrderBy(stage => stage.QualifiedTypeName, StringComparer.Ordinal).ToArray();
                if (entries.Length <= 1) continue;

                foreach (var entry in entries) duplicateTypes.Add(entry.StageType);
            }

            stages.RemoveAll(stage => duplicateTypes.Contains(stage.StageType));
            stages.Sort((left, right) => string.CompareOrdinal(left.QualifiedTypeName, right.QualifiedTypeName));
            context.AddSource("MobaGeneratedBootstrapStageManifest.g.cs", GenerateSource(stages));
        }

        private static string GenerateSource(IReadOnlyList<StageMapping> stages)
        {
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace AbilityKit.Demo.Moba.Systems.Bootstrap.Flow");
            source.AppendLine("{");
            source.AppendLine("    internal static partial class MobaGeneratedBootstrapStageManifest");
            source.AppendLine("    {");
            source.AppendLine("        static partial void AddGenerated(ref int count)");
            source.AppendLine("        {");
            foreach (var stage in stages)
            {
                source.Append("            Register(() => new ")
                    .Append(stage.QualifiedTypeName).Append("(), ")
                    .Append(Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(stage.QualifiedTypeName, true))
                    .AppendLine(", ref count);");
            }

            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

        private sealed class StageMapping
        {
            public StageMapping(INamedTypeSymbol stageType, string? stageName)
            {
                StageType = stageType;
                StageName = stageName;
                QualifiedTypeName = stageType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }

            public INamedTypeSymbol StageType { get; }
            public string? StageName { get; }
            public string QualifiedTypeName { get; }
        }
    }

    internal sealed class BootstrapStageSyntaxReceiver : ISyntaxContextReceiver
    {
        public List<INamedTypeSymbol> Types { get; } = new List<INamedTypeSymbol>();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            if (context.Node is ClassDeclarationSyntax declaration && declaration.AttributeLists.Count > 0 &&
                context.SemanticModel.GetDeclaredSymbol(declaration) is INamedTypeSymbol type)
            {
                Types.Add(type);
            }
        }
    }
}
