using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AbilityKit.Demo.Moba.CodeGen
{
    [Generator]
    public sealed class MobaPayloadFieldIdsGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new PayloadFieldIdsSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is PayloadFieldIdsSyntaxReceiver receiver))
            {
                return;
            }

            var attributeType = context.Compilation.GetTypeByMetadataName(
                MobaPayloadFieldIdsContract.AttributeMetadataName);
            if (attributeType == null)
            {
                return;
            }

            var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var type in receiver.Types)
            {
                if (!seen.Add(type))
                {
                    continue;
                }

                var attributes = type.GetAttributes()
                    .Where(candidate => SymbolEqualityComparer.Default.Equals(candidate.AttributeClass, attributeType))
                    .ToArray();
                if (attributes.Length == 0)
                {
                    continue;
                }

                var validation = MobaPayloadFieldIdsContract.Validate(
                    context.Compilation,
                    type,
                    attributes);
                if (validation.IsValid)
                {
                    context.AddSource(GetHintName(type), GenerateSource(type, validation.Groups));
                }
            }
        }

        private static string GenerateSource(
            INamedTypeSymbol type,
            IReadOnlyList<MobaPayloadFieldGroup> groups)
        {
            var fields = new Dictionary<string, GeneratedField>(StringComparer.Ordinal);
            foreach (var group in groups)
            {
                foreach (var field in group.Fields)
                {
                    if (fields.TryGetValue(field.Name, out var existing))
                    {
                        if (!string.Equals(existing.CatalogType, group.CatalogTypeName, StringComparison.Ordinal))
                        {
                            continue;
                        }

                        existing.IncludeLegacyIds |= field.IncludeLegacyIds;
                    }
                    else
                    {
                        fields.Add(field.Name, new GeneratedField(
                            group.CatalogTypeName,
                            field.Name,
                            field.IncludeLegacyIds));
                    }
                }
            }

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            if (!type.ContainingNamespace.IsGlobalNamespace)
            {
                source.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine();
                source.AppendLine("{");
            }

            var indent = type.ContainingNamespace.IsGlobalNamespace ? string.Empty : "    ";
            source.Append(indent)
                .Append(GetAccessibility(type.DeclaredAccessibility))
                .Append(GetTypeModifiers(type))
                .Append(" partial class ")
                .Append(type.Name)
                .AppendLine();
            source.Append(indent).AppendLine("{");

            foreach (var field in fields.Values.OrderBy(item => item.Name, StringComparer.Ordinal))
            {
                source.Append(indent).Append("    private static readonly int ")
                    .Append(field.Name).Append("Id = ")
                    .Append(field.CatalogType).Append(".FieldId(")
                    .Append(field.CatalogType).Append('.').Append(field.Name).AppendLine(");");
                if (field.IncludeLegacyIds)
                {
                    source.Append(indent).Append("    private static readonly int ")
                        .Append(field.Name).Append("LegacyId = ")
                        .Append(field.CatalogType).Append(".LegacyFieldId(")
                        .Append(field.CatalogType).Append('.').Append(field.Name).AppendLine(");");
                }
            }

            foreach (var group in groups.OrderBy(item => item.MethodName, StringComparer.Ordinal))
            {
                source.AppendLine();
                source.Append(indent).Append("    public static bool ")
                    .Append(group.MethodName).AppendLine("(int fieldId)");
                source.Append(indent).AppendLine("    {");
                source.Append(indent).Append("        return ");
                for (var index = 0; index < group.Fields.Count; index++)
                {
                    var field = group.Fields[index];
                    if (index > 0)
                    {
                        source.AppendLine().Append(indent).Append("            || ");
                    }

                    source.Append("fieldId == ").Append(field.Name).Append("Id");
                    if (field.IncludeLegacyIds)
                    {
                        source.Append(" || fieldId == ").Append(field.Name).Append("LegacyId");
                    }
                }

                source.AppendLine(";");
                source.Append(indent).AppendLine("    }");
            }

            source.Append(indent).AppendLine("}");
            if (!type.ContainingNamespace.IsGlobalNamespace)
            {
                source.AppendLine("}");
            }

            return source.ToString();
        }

        private static string GetAccessibility(Accessibility accessibility)
        {
            return accessibility == Accessibility.Public ? "public" : "internal";
        }

        private static string GetTypeModifiers(INamedTypeSymbol type)
        {
            if (type.IsStatic) return " static";
            if (type.IsSealed) return " sealed";
            if (type.IsAbstract) return " abstract";
            return string.Empty;
        }

        private static string GetHintName(INamedTypeSymbol type)
        {
            var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", string.Empty)
                .Replace('.', '_');
            return name + ".PayloadFieldIds.g.cs";
        }

        private sealed class GeneratedField
        {
            public GeneratedField(string catalogType, string name, bool includeLegacyIds)
            {
                CatalogType = catalogType;
                Name = name;
                IncludeLegacyIds = includeLegacyIds;
            }

            public string CatalogType { get; }
            public string Name { get; }
            public bool IncludeLegacyIds { get; set; }
        }
    }

    internal sealed class PayloadFieldIdsSyntaxReceiver : ISyntaxContextReceiver
    {
        public List<INamedTypeSymbol> Types { get; } = new List<INamedTypeSymbol>();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            if (context.Node is ClassDeclarationSyntax declaration && declaration.AttributeLists.Count > 0 &&
                context.SemanticModel.GetDeclaredSymbol(declaration) is INamedTypeSymbol type)
            {
                Types.Add(type);
            }
        }
    }
}
