using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace AbilityKit.Demo.Moba.CodeGen
{
    [Generator]
    public sealed class MobaConfigTableManifestGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public void Execute(GeneratorExecutionContext context)
        {
            var attributeType = context.Compilation.GetTypeByMetadataName(
                MobaConfigTableContract.AttributeMetadataName);
            var manifestType = context.Compilation.GetTypeByMetadataName(
                MobaConfigTableContract.ManifestMetadataName);
            if (attributeType == null || !MobaConfigTableContract.IsSourceManifest(manifestType)) return;

            var specs = new List<MobaConfigTableSpec>();
            foreach (var attribute in context.Compilation.Assembly.GetAttributes())
            {
                if (!SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, attributeType)) continue;
                if (MobaConfigTableContract.TryCreateSpec(attribute, out var spec, out _)) specs.Add(spec);
            }

            specs.Sort(CompareSpecs);
            var uniqueSpecs = RemoveDuplicates(specs);
            context.AddSource("MobaGeneratedConfigTableManifest.g.cs", GenerateSource(uniqueSpecs));
        }

        private static int CompareSpecs(MobaConfigTableSpec left, MobaConfigTableSpec right)
        {
            var order = left.Order.CompareTo(right.Order);
            if (order != 0) return order;
            var path = string.CompareOrdinal(left.FilePath, right.FilePath);
            if (path != 0) return path;
            return string.CompareOrdinal(left.QualifiedDtoTypeName, right.QualifiedDtoTypeName);
        }

        private static IReadOnlyList<MobaConfigTableSpec> RemoveDuplicates(
            IReadOnlyList<MobaConfigTableSpec> specs)
        {
            var result = new List<MobaConfigTableSpec>(specs.Count);
            var uniqueness = new MobaConfigTableUniquenessTracker();
            foreach (var spec in specs)
            {
                if (!uniqueness.TryAdd(spec, out _, out _)) continue;
                result.Add(spec);
            }

            return result;
        }

        private static string GenerateSource(IReadOnlyList<MobaConfigTableSpec> specs)
        {
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace AbilityKit.Demo.Moba.Config.Core");
            source.AppendLine("{");
            source.AppendLine("    internal static partial class MobaGeneratedConfigTableManifest");
            source.AppendLine("    {");
            source.AppendLine("        static partial void AddGenerated(System.Collections.Generic.List<MobaConfigTableSpec> specs, ref int count)");
            source.AppendLine("        {");
            for (var i = 0; i < specs.Count; i++)
            {
                var spec = specs[i];
                source.Append("            specs.Add(new MobaConfigTableSpec(")
                    .Append(Literal(spec.FilePath)).Append(", typeof(")
                    .Append(spec.QualifiedDtoTypeName).Append("), typeof(")
                    .Append(spec.QualifiedMoTypeName).Append("), ")
                    .Append(Literal(spec.GroupName)).Append(", ")
                    .Append(spec.Order).Append(", CreateDtoTable").Append(i)
                    .Append(", CreateEntryTable").Append(i)
                    .Append(", CollectChangedIds").Append(i).AppendLine("));");
                source.AppendLine("            count++;");
            }

            source.AppendLine("        }");
            for (var i = 0; i < specs.Count; i++)
            {
                var spec = specs[i];
                source.Append("        private static object CreateDtoTable").Append(i)
                    .AppendLine("(System.Array source)");
                source.AppendLine("        {");
                source.Append("            return global::AbilityKit.Ability.Config.ConfigTableFactory.CreateDtoTable<")
                    .Append(spec.QualifiedDtoTypeName).Append(">(source, dto => dto.")
                    .Append(spec.KeyMemberName).AppendLine(");");
                source.AppendLine("        }");
                source.Append("        private static object CreateEntryTable").Append(i)
                    .AppendLine("(System.Array source)");
                source.AppendLine("        {");
                source.Append("            return global::AbilityKit.Ability.Config.ConfigTableFactory.CreateEntryTable<")
                    .Append(spec.QualifiedDtoTypeName).Append(", ")
                    .Append(spec.QualifiedMoTypeName).Append(">(source, dto => dto.")
                    .Append(spec.KeyMemberName).Append(", dto => new ")
                    .Append(spec.QualifiedMoTypeName).AppendLine("(dto));");
                source.AppendLine("        }");
                source.Append("        private static void CollectChangedIds").Append(i)
                    .AppendLine("(System.Array source, System.Collections.Generic.ISet<int> changedIds)");
                source.AppendLine("        {");
                source.Append("            global::AbilityKit.Ability.Config.ConfigTableFactory.CollectChangedIds<")
                    .Append(spec.QualifiedDtoTypeName).Append(">(source, changedIds, dto => dto.")
                    .Append(spec.KeyMemberName).AppendLine(");");
                source.AppendLine("        }");
            }

            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

        private static string Literal(string value)
        {
            return Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);
        }
    }
}
