using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AbilityKit.Demo.Moba.CodeGen
{
    [Generator]
    public sealed class MobaPlanActionManifestGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new MobaPlanActionSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is MobaPlanActionSyntaxReceiver receiver))
            {
                return;
            }

            var attributeType = context.Compilation.GetTypeByMetadataName(
                MobaPlanActionContract.AttributeMetadataName);
            var moduleBaseType = context.Compilation.GetTypeByMetadataName(
                MobaPlanActionContract.ModuleBaseMetadataName);
            var manifestType = context.Compilation.GetTypeByMetadataName(
                MobaPlanActionContract.ManifestMetadataName);
            if (attributeType == null || moduleBaseType == null || manifestType == null ||
                !manifestType.Locations.Any(location => location.IsInSource))
            {
                return;
            }

            var modules = new List<ModuleInfo>();
            var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var type in receiver.Types)
            {
                if (!seen.Add(type))
                {
                    continue;
                }

                var attribute = type.GetAttributes().FirstOrDefault(candidate =>
                    SymbolEqualityComparer.Default.Equals(candidate.AttributeClass, attributeType));
                if (attribute == null ||
                    !MobaPlanActionContract.IsValidForGeneration(type, moduleBaseType))
                {
                    continue;
                }

                modules.Add(new ModuleInfo(type, MobaPlanActionContract.ResolveOrder(attribute)));
            }

            modules.Sort((left, right) =>
            {
                var order = left.Order.CompareTo(right.Order);
                return order != 0
                    ? order
                    : string.CompareOrdinal(left.FullName, right.FullName);
            });

            context.AddSource("MobaGeneratedPlanActionManifest.g.cs", GenerateSource(modules));
        }

        private static string GenerateSource(IReadOnlyList<ModuleInfo> modules)
        {
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace AbilityKit.Demo.Moba.Services.Triggering.PlanActions");
            source.AppendLine("{");
            source.AppendLine("    internal static partial class MobaGeneratedPlanActionManifest");
            source.AppendLine("    {");
            source.AppendLine("        static partial void AddGenerated(global::System.Collections.Generic.List<MobaPlanActionDescriptor> descriptors)");
            source.AppendLine("        {");
            foreach (var module in modules)
            {
                source.Append("            Add<")
                    .Append(module.QualifiedName)
                    .Append(">(descriptors, ")
                    .Append(module.Order)
                    .AppendLine(");");
            }

            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

        private sealed class ModuleInfo
        {
            public ModuleInfo(INamedTypeSymbol type, int order)
            {
                Order = order;
                FullName = type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
                QualifiedName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }

            public int Order { get; }
            public string FullName { get; }
            public string QualifiedName { get; }
        }
    }

    internal sealed class MobaPlanActionSyntaxReceiver : ISyntaxContextReceiver
    {
        public List<INamedTypeSymbol> Types { get; } = new List<INamedTypeSymbol>();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            if (context.Node is ClassDeclarationSyntax declaration && declaration.AttributeLists.Count > 0 &&
                context.SemanticModel.GetDeclaredSymbol(declaration) is INamedTypeSymbol type)
            {
                Types.Add(type);
            }
        }
    }
}
