using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AbilityKit.Demo.Moba.CodeGen
{
    [Generator]
    public sealed class MobaSnapshotEmitterManifestGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new SnapshotEmitterSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is SnapshotEmitterSyntaxReceiver receiver)) return;

            var attributeType = context.Compilation.GetTypeByMetadataName(
                MobaSnapshotEmitterContract.AttributeMetadataName);
            var interfaceType = context.Compilation.GetTypeByMetadataName(
                MobaSnapshotEmitterContract.InterfaceMetadataName);
            var manifestType = context.Compilation.GetTypeByMetadataName(
                MobaSnapshotEmitterContract.ManifestMetadataName);
            if (attributeType == null || interfaceType == null ||
                !MobaSnapshotEmitterContract.IsSourceManifest(manifestType)) return;

            var emitters = new List<MobaSnapshotEmitterMapping>();
            var seenTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var type in receiver.Types)
            {
                if (!seenTypes.Add(type)) continue;

                var attribute = type.GetAttributes().FirstOrDefault(candidate =>
                    SymbolEqualityComparer.Default.Equals(candidate.AttributeClass, attributeType));
                if (attribute == null) continue;

                if (!MobaSnapshotEmitterContract.TryCreateMapping(
                        type,
                        interfaceType,
                        attribute,
                        out var mapping,
                        out _))
                {
                    continue;
                }

                emitters.Add(mapping);
            }

            emitters.Sort(CompareEmitters);
            context.AddSource("MobaGeneratedSnapshotEmitterManifest.g.cs", GenerateSource(emitters));
        }

        private static int CompareEmitters(
            MobaSnapshotEmitterMapping left,
            MobaSnapshotEmitterMapping right)
        {
            var priority = left.Priority.CompareTo(right.Priority);
            return priority != 0
                ? priority
                : string.CompareOrdinal(left.QualifiedTypeName, right.QualifiedTypeName);
        }

        private static string GenerateSource(IReadOnlyList<MobaSnapshotEmitterMapping> emitters)
        {
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace AbilityKit.Demo.Moba.Services");
            source.AppendLine("{");
            source.AppendLine("    internal static partial class MobaGeneratedSnapshotEmitterManifest");
            source.AppendLine("    {");
            source.AppendLine("        static partial void AddGenerated(MobaSnapshotEmitterRegistry registry, ref int count)");
            source.AppendLine("        {");
            foreach (var emitter in emitters)
            {
                source.Append("            if (registry.TryRegisterGenerated(").Append(emitter.Priority)
                    .Append(", typeof(").Append(emitter.QualifiedTypeName).AppendLine("))) count++;");
            }

            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

    }

    internal sealed class SnapshotEmitterSyntaxReceiver : ISyntaxContextReceiver
    {
        public List<INamedTypeSymbol> Types { get; } = new List<INamedTypeSymbol>();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            if (context.Node is ClassDeclarationSyntax declaration && declaration.AttributeLists.Count > 0 &&
                context.SemanticModel.GetDeclaredSymbol(declaration) is INamedTypeSymbol type)
            {
                Types.Add(type);
            }
        }
    }
}
