using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AbilityKit.Demo.Moba.CodeGen
{
    [Generator]
    public sealed class MobaRegistrationManifestGenerator : ISourceGenerator
    {
        private const string ArchetypeAttributeName = "AbilityKit.Demo.Moba.Services.EntityConstruction.MobaActorArchetypeAttribute";
        private const string InitializerAttributeName = "AbilityKit.Demo.Moba.Services.EntityConstruction.MobaActorInitializerAttribute";
        private const string InitializerInterfaceName = "AbilityKit.Demo.Moba.Services.EntityConstruction.IMobaActorInitializerStep";
        private const string DamageAttributeName = "AbilityKit.Demo.Moba.Services.MobaDamageStageAttribute";
        private const string DamageInterfaceName = "AbilityKit.Demo.Moba.Services.IMobaDamagePipelineStage";
        private const string SkillPhaseAttributeName = "AbilityKit.Demo.Moba.Services.MobaSkillPhaseAttribute";
        private const string RollbackAttributeName = "AbilityKit.Demo.Moba.Rollback.MobaRollbackProviderAttribute";
        private const string RollbackInterfaceName = "AbilityKit.Ability.FrameSync.Rollback.IRollbackStateProvider";
        private const string ArchetypeAssemblerName = "AbilityKit.Demo.Moba.Services.EntityConstruction.MobaActorArchetypeAssembler";
        private const string InitializerManifestName = "AbilityKit.Demo.Moba.Services.EntityConstruction.MobaGeneratedActorInitializerManifest";
        private const string DamageManifestName = "AbilityKit.Demo.Moba.Services.MobaGeneratedDamageStageManifest";
        private const string SkillPhaseManifestName = "AbilityKit.Demo.Moba.Services.MobaGeneratedSkillPhaseManifest";
        private const string RollbackManifestName = "AbilityKit.Demo.Moba.Rollback.MobaGeneratedRollbackProviderManifest";

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new Receiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is Receiver receiver)) return;
            if (IsDeclaredInSource(context.Compilation, ArchetypeAssemblerName))
                GenerateArchetypes(context, receiver.Methods);
            if (IsDeclaredInSource(context.Compilation, InitializerManifestName))
                GenerateInitializers(context, receiver.Types);
            if (IsDeclaredInSource(context.Compilation, DamageManifestName))
                GenerateDamageStages(context, receiver.Types);
            if (IsDeclaredInSource(context.Compilation, SkillPhaseManifestName))
                GenerateSkillPhases(context, receiver.Types);
            if (IsDeclaredInSource(context.Compilation, RollbackManifestName))
                GenerateRollbackProviders(context, receiver.Types);
        }

        private static void GenerateArchetypes(GeneratorExecutionContext context, IReadOnlyList<IMethodSymbol> methods)
        {
            var attributeType = context.Compilation.GetTypeByMetadataName(ArchetypeAttributeName);
            if (attributeType == null) return;
            var entries = new List<ArchetypeEntry>();
            foreach (var method in Distinct(methods))
            {
                var attribute = method.GetAttributes().FirstOrDefault(item => SymbolEqualityComparer.Default.Equals(item.AttributeClass, attributeType));
                if (attribute == null) continue;
                if (!method.IsStatic || method.Parameters.Length != 2 || method.Parameters[1].RefKind != RefKind.In)
                {
                    ReportInvalid(context, method, "archetype factory must be static and have parameters (ActorContext, in MobaEntityInfo)");
                    continue;
                }
                var kind = ReadInt(attribute, 0, 0);
                if (kind <= 0)
                {
                    ReportInvalid(context, method, "archetype kind must not be Unknown");
                    continue;
                }
                entries.Add(new ArchetypeEntry(method, kind));
            }
            ReportDuplicates(context, entries, item => item.Kind.ToString(), item => item.Method);
            entries.Sort((left, right) => left.Kind.CompareTo(right.Kind));

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace AbilityKit.Demo.Moba.Services.EntityConstruction");
            source.AppendLine("{");
            source.AppendLine("    public static partial class MobaActorArchetypeAssembler");
            source.AppendLine("    {");
            source.AppendLine("        static partial void AddGenerated(MobaActorArchetypeRegistry registry)");
            source.AppendLine("        {");
            foreach (var entry in entries)
            {
                source.Append("            registry.Register((MobaEntityKind)").Append(entry.Kind).Append(", ")
                    .Append(entry.Method.Name).AppendLine(");");
            }
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            context.AddSource("MobaGeneratedActorArchetypeManifest.g.cs", source.ToString());
        }

        private static void GenerateInitializers(GeneratorExecutionContext context, IReadOnlyList<INamedTypeSymbol> types)
        {
            var attributeType = context.Compilation.GetTypeByMetadataName(InitializerAttributeName);
            var interfaceType = context.Compilation.GetTypeByMetadataName(InitializerInterfaceName);
            if (attributeType == null || interfaceType == null) return;
            var entries = new List<RegistrationEntry>();
            foreach (var type in Distinct(types))
            {
                var attribute = type.GetAttributes().FirstOrDefault(item => SymbolEqualityComparer.Default.Equals(item.AttributeClass, attributeType));
                if (attribute == null) continue;
                var id = ReadString(attribute, 0);
                var order = ReadInt(attribute, 1, 0);
                if (string.IsNullOrWhiteSpace(id) || !Implements(type, interfaceType))
                {
                    ReportInvalid(context, type, "initializer id is required and type must implement IMobaActorInitializerStep");
                    continue;
                }
                entries.Add(new RegistrationEntry(type, id!, order, null, false));
            }
            ValidateIdAndOrder(context, entries, includeOrder: true);
            entries.Sort(RegistrationEntry.Compare);
            context.AddSource("MobaGeneratedActorInitializerManifest.g.cs", BuildDescriptorSource(
                "AbilityKit.Demo.Moba.Services.EntityConstruction",
                "MobaGeneratedActorInitializerManifest",
                "MobaGeneratedRegistrationDescriptor",
                entries,
                damage: false));
        }

        private static void GenerateDamageStages(GeneratorExecutionContext context, IReadOnlyList<INamedTypeSymbol> types)
        {
            var attributeType = context.Compilation.GetTypeByMetadataName(DamageAttributeName);
            var interfaceType = context.Compilation.GetTypeByMetadataName(DamageInterfaceName);
            if (attributeType == null || interfaceType == null) return;
            var entries = new List<RegistrationEntry>();
            foreach (var type in Distinct(types))
            {
                var attribute = type.GetAttributes().FirstOrDefault(item => SymbolEqualityComparer.Default.Equals(item.AttributeClass, attributeType));
                if (attribute == null) continue;
                var id = ReadString(attribute, 0);
                var order = ReadInt(attribute, 1, 0);
                var eventId = ReadString(attribute, 2);
                var isCore = ReadBool(attribute, 3, false);
                if (string.IsNullOrWhiteSpace(id) || string.IsNullOrWhiteSpace(eventId) || !Implements(type, interfaceType))
                {
                    ReportInvalid(context, type, "stage id/event id are required and type must implement IMobaDamagePipelineStage");
                    continue;
                }
                if (!isCore && !((order > 1000 && order < 2000) || (order > 2000 && order < 3000) || (order > 3000 && order < 4000)))
                {
                    ReportInvalid(context, type, "extension stage order must be inside a protected extension interval");
                    continue;
                }
                entries.Add(new RegistrationEntry(type, id!, order, eventId, isCore));
            }
            ValidateIdAndOrder(context, entries, includeOrder: false);
            ReportDuplicates(context, entries, item => item.EventId!, item => item.Type);
            entries.Sort(RegistrationEntry.Compare);
            context.AddSource("MobaGeneratedDamageStageManifest.g.cs", BuildDescriptorSource(
                "AbilityKit.Demo.Moba.Services",
                "MobaGeneratedDamageStageManifest",
                "MobaGeneratedDamageStageDescriptor",
                entries,
                damage: true));
        }

        private static void GenerateSkillPhases(GeneratorExecutionContext context, IReadOnlyList<INamedTypeSymbol> types)
        {
            var attributeType = context.Compilation.GetTypeByMetadataName(SkillPhaseAttributeName);
            if (attributeType == null) return;
            var entries = new List<SkillPhaseEntry>();
            foreach (var type in Distinct(types))
            {
                foreach (var attribute in type.GetAttributes().Where(item => SymbolEqualityComparer.Default.Equals(item.AttributeClass, attributeType)))
                {
                    entries.Add(new SkillPhaseEntry(type, ReadInt(attribute, 0, 0)));
                }
            }
            ReportDuplicates(context, entries, item => item.PhaseType.ToString(), item => item.Type);
            entries.Sort((left, right) => left.PhaseType.CompareTo(right.PhaseType));

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace AbilityKit.Demo.Moba.Services");
            source.AppendLine("{");
            source.AppendLine("    internal static partial class MobaGeneratedSkillPhaseManifest");
            source.AppendLine("    {");
            source.AppendLine("        static partial void AddGenerated(global::System.Collections.Generic.HashSet<int> phaseTypes)");
            source.AppendLine("        {");
            foreach (var entry in entries) source.Append("            phaseTypes.Add(").Append(entry.PhaseType).AppendLine(");");
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            context.AddSource("MobaGeneratedSkillPhaseManifest.g.cs", source.ToString());
        }

        private static void GenerateRollbackProviders(GeneratorExecutionContext context, IReadOnlyList<INamedTypeSymbol> types)
        {
            var attributeType = context.Compilation.GetTypeByMetadataName(RollbackAttributeName);
            var interfaceType = context.Compilation.GetTypeByMetadataName(RollbackInterfaceName);
            if (attributeType == null || interfaceType == null) return;

            var entries = new List<RollbackEntry>();
            foreach (var type in Distinct(types))
            {
                var isProvider = Implements(type, interfaceType);
                var attribute = type.GetAttributes().FirstOrDefault(item => SymbolEqualityComparer.Default.Equals(item.AttributeClass, attributeType));
                if (!isProvider && attribute == null) continue;
                if (!isProvider)
                {
                    ReportInvalid(context, type, "type marked as rollback provider must implement IRollbackStateProvider");
                    continue;
                }
                if (attribute == null)
                {
                    ReportInvalid(context, type, "rollback provider is missing MobaRollbackProviderAttribute");
                    continue;
                }

                var key = ReadInt(attribute, 0, 0);
                var autoResolve = ReadBool(attribute, 1, false);
                if (key <= 0)
                {
                    ReportInvalid(context, type, "rollback provider key must be positive");
                    continue;
                }
                if (autoResolve && type.DeclaredAccessibility == Accessibility.Private)
                {
                    ReportInvalid(context, type, "auto-resolved rollback provider must be accessible from generated manifest code");
                    continue;
                }
                entries.Add(new RollbackEntry(type, key, autoResolve));
            }

            ReportDuplicates(context, entries, item => item.Key.ToString(), item => item.Type);
            entries.Sort((left, right) => left.Key.CompareTo(right.Key));

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace AbilityKit.Demo.Moba.Rollback");
            source.AppendLine("{");
            source.AppendLine("    internal static partial class MobaGeneratedRollbackProviderManifest");
            source.AppendLine("    {");
            source.AppendLine("        static partial void AddGeneratedDescriptors(global::System.Collections.Generic.List<MobaGeneratedRollbackProviderDescriptor> descriptors)");
            source.AppendLine("        {");
            foreach (var entry in entries)
            {
                source.Append("            descriptors.Add(new MobaGeneratedRollbackProviderDescriptor(")
                    .Append(entry.Key).Append(", \"")
                    .Append(Escape(entry.Type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat))).Append("\", ")
                    .Append(entry.AutoResolve ? "true" : "false").AppendLine("));");
            }
            source.AppendLine("        }");
            source.AppendLine();
            source.AppendLine("        static partial void AddGeneratedResolved(global::AbilityKit.Ability.World.DI.IWorldResolver services, global::AbilityKit.Ability.FrameSync.Rollback.RollbackRegistry registry)");
            source.AppendLine("        {");
            var index = 0;
            foreach (var entry in entries.Where(item => item.AutoResolve))
            {
                var typeName = entry.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                source.Append("            if (services.TryResolve<").Append(typeName).Append(">(out var provider")
                    .Append(index).Append(") && provider").Append(index).AppendLine(" != null)");
                source.Append("                registry.Register(provider").Append(index).AppendLine(");");
                index++;
            }
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            context.AddSource("MobaGeneratedRollbackProviderManifest.g.cs", source.ToString());
        }

        private static string BuildDescriptorSource(
            string namespaceName,
            string manifestName,
            string descriptorName,
            IReadOnlyList<RegistrationEntry> entries,
            bool damage)
        {
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.Append("namespace ").Append(namespaceName).AppendLine();
            source.AppendLine("{");
            source.Append("    internal static partial class ").Append(manifestName).AppendLine();
            source.AppendLine("    {");
            source.Append("        static partial void AddGenerated(global::System.Collections.Generic.List<").Append(descriptorName).AppendLine("> descriptors)");
            source.AppendLine("        {");
            foreach (var entry in entries)
            {
                source.Append("            descriptors.Add(new ").Append(descriptorName).Append("(\"")
                    .Append(Escape(entry.Id)).Append("\", ").Append(entry.Order).Append(", ");
                if (damage)
                {
                    source.Append("\"").Append(Escape(entry.EventId!)).Append("\", ")
                        .Append(entry.IsCore ? "true" : "false").Append(", ");
                }
                source.Append("\"").Append(Escape(entry.Type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)))
                    .AppendLine("\"));");
            }
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

        private static void ValidateIdAndOrder(GeneratorExecutionContext context, IReadOnlyList<RegistrationEntry> entries, bool includeOrder)
        {
            ReportDuplicates(context, entries, item => item.Id, item => item.Type);
            if (includeOrder) ReportDuplicates(context, entries, item => item.Order.ToString(), item => item.Type);
        }

        private static void ReportDuplicates<T>(
            GeneratorExecutionContext context,
            IReadOnlyList<T> entries,
            Func<T, string> keySelector,
            Func<T, ISymbol> symbolSelector)
        {
            foreach (var group in entries.GroupBy(keySelector, StringComparer.Ordinal).Where(group => group.Count() > 1))
            {
                var values = group.ToArray();
                var first = symbolSelector(values[0]);
                for (var i = 1; i < values.Length; i++)
                {
                    var current = symbolSelector(values[i]);
                    context.ReportDiagnostic(Diagnostic.Create(
                        MobaDiagnosticRules.DuplicateRegistrationManifestKeyRule,
                        current.Locations.FirstOrDefault(),
                        group.Key,
                        first.ToDisplayString(),
                        current.ToDisplayString()));
                }
            }
        }

        private static void ReportInvalid(GeneratorExecutionContext context, ISymbol symbol, string message)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                MobaDiagnosticRules.InvalidRegistrationManifestRule,
                symbol.Locations.FirstOrDefault(),
                symbol.ToDisplayString(),
                message));
        }

        private static bool Implements(INamedTypeSymbol type, INamedTypeSymbol interfaceType) =>
            type.AllInterfaces.Any(item => SymbolEqualityComparer.Default.Equals(item, interfaceType));

        private static bool IsDeclaredInSource(Compilation compilation, string metadataName)
        {
            var type = compilation.GetTypeByMetadataName(metadataName);
            return type != null && type.Locations.Any(location => location.IsInSource);
        }

        private static int ReadInt(AttributeData attribute, int index, int fallback) =>
            attribute.ConstructorArguments.Length > index && attribute.ConstructorArguments[index].Value is int value ? value : fallback;

        private static bool ReadBool(AttributeData attribute, int index, bool fallback) =>
            attribute.ConstructorArguments.Length > index && attribute.ConstructorArguments[index].Value is bool value ? value : fallback;

        private static string? ReadString(AttributeData attribute, int index) =>
            attribute.ConstructorArguments.Length > index ? attribute.ConstructorArguments[index].Value as string : null;

        private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static IEnumerable<INamedTypeSymbol> Distinct(IEnumerable<INamedTypeSymbol> values)
        {
            var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var value in values) if (seen.Add(value)) yield return value;
        }

        private static IEnumerable<IMethodSymbol> Distinct(IEnumerable<IMethodSymbol> values)
        {
            var seen = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);
            foreach (var value in values) if (seen.Add(value)) yield return value;
        }

        private sealed class ArchetypeEntry
        {
            public ArchetypeEntry(IMethodSymbol method, int kind) { Method = method; Kind = kind; }
            public IMethodSymbol Method { get; }
            public int Kind { get; }
        }

        private sealed class RegistrationEntry
        {
            public RegistrationEntry(INamedTypeSymbol type, string id, int order, string? eventId, bool isCore)
            { Type = type; Id = id; Order = order; EventId = eventId; IsCore = isCore; }
            public INamedTypeSymbol Type { get; }
            public string Id { get; }
            public int Order { get; }
            public string? EventId { get; }
            public bool IsCore { get; }
            public static int Compare(RegistrationEntry left, RegistrationEntry right)
            {
                var result = left.Order.CompareTo(right.Order);
                return result != 0 ? result : string.CompareOrdinal(left.Id, right.Id);
            }
        }

        private sealed class SkillPhaseEntry
        {
            public SkillPhaseEntry(INamedTypeSymbol type, int phaseType) { Type = type; PhaseType = phaseType; }
            public INamedTypeSymbol Type { get; }
            public int PhaseType { get; }
        }

        private sealed class RollbackEntry
        {
            public RollbackEntry(INamedTypeSymbol type, int key, bool autoResolve)
            {
                Type = type;
                Key = key;
                AutoResolve = autoResolve;
            }

            public INamedTypeSymbol Type { get; }
            public int Key { get; }
            public bool AutoResolve { get; }
        }

        private sealed class Receiver : ISyntaxContextReceiver
        {
            public List<INamedTypeSymbol> Types { get; } = new List<INamedTypeSymbol>();
            public List<IMethodSymbol> Methods { get; } = new List<IMethodSymbol>();

            public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
            {
                if (context.Node is TypeDeclarationSyntax typeDeclaration && typeDeclaration.AttributeLists.Count > 0 &&
                    context.SemanticModel.GetDeclaredSymbol(typeDeclaration) is INamedTypeSymbol type)
                    Types.Add(type);
                else if (context.Node is MethodDeclarationSyntax methodDeclaration && methodDeclaration.AttributeLists.Count > 0 &&
                         context.SemanticModel.GetDeclaredSymbol(methodDeclaration) is IMethodSymbol method)
                    Methods.Add(method);
            }
        }
    }
}
