using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AbilityKit.Demo.Moba.CodeGen
{
    [Generator]
    public sealed class MobaTargetQueryFactoryManifestGenerator : ISourceGenerator
    {
        private const string ManifestMetadataName =
            "AbilityKit.Demo.Moba.Services.Search.MobaGeneratedTargetQueryFactoryManifest";

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new TargetQueryFactorySyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is TargetQueryFactorySyntaxReceiver receiver))
            {
                return;
            }

            var manifestType = context.Compilation.GetTypeByMetadataName(ManifestMetadataName);
            if (manifestType == null || !manifestType.Locations.Any(location => location.IsInSource))
            {
                return;
            }

            var resolvedDefinitions = MobaTargetQueryFactoryContract.ResolveDefinitions(context.Compilation);
            if (resolvedDefinitions.Count == 0)
            {
                return;
            }

            var mappings = new List<MobaTargetQueryFactoryMapping>();
            var seenTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var type in receiver.Types)
            {
                if (!seenTypes.Add(type))
                {
                    continue;
                }

                foreach (var definition in resolvedDefinitions)
                {
                    var attributes = type.GetAttributes().Where(attribute =>
                        SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, definition.AttributeType));
                    foreach (var attribute in attributes)
                    {
                        if (!MobaTargetQueryFactoryContract.TryCreateMapping(
                                type,
                                definition,
                                attribute,
                                out var mapping,
                                out _))
                        {
                            continue;
                        }

                        mappings.Add(mapping);
                    }
                }
            }

            var validMappings = new List<MobaTargetQueryFactoryMapping>();
            foreach (var group in mappings.GroupBy(
                         MobaTargetQueryFactoryContract.GetDuplicateKey,
                         StringComparer.Ordinal))
            {
                var entries = group.ToArray();
                if (entries.Length > 1)
                {
                    continue;
                }

                validMappings.Add(entries[0]);
            }

            validMappings.Sort(CompareMappings);
            context.AddSource("MobaGeneratedTargetQueryFactoryManifest.g.cs", GenerateSource(validMappings));
        }

        private static int CompareMappings(
            MobaTargetQueryFactoryMapping left,
            MobaTargetQueryFactoryMapping right)
        {
            var kind = string.CompareOrdinal(left.Definition.Kind, right.Definition.Kind);
            if (kind != 0) return kind;
            var code = left.Code.CompareTo(right.Code);
            if (code != 0) return code;
            return string.CompareOrdinal(left.QualifiedTypeName, right.QualifiedTypeName);
        }

        private static string GenerateSource(IReadOnlyList<MobaTargetQueryFactoryMapping> mappings)
        {
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace AbilityKit.Demo.Moba.Services.Search");
            source.AppendLine("{");
            source.AppendLine("    internal static partial class MobaGeneratedTargetQueryFactoryManifest");
            source.AppendLine("    {");
            source.AppendLine("        static partial void AddGenerated(MobaTargetQueryFactoryRegistry registry, ref int count)");
            source.AppendLine("        {");
            foreach (var mapping in mappings)
            {
                source.Append("            registry.")
                    .Append(mapping.Definition.RegisterMethod)
                    .Append('(').Append(mapping.Code).Append(", new ")
                    .Append(mapping.QualifiedTypeName).AppendLine("());");
                source.AppendLine("            count++;");
            }

            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

    }

    internal sealed class TargetQueryFactorySyntaxReceiver : ISyntaxContextReceiver
    {
        public List<INamedTypeSymbol> Types { get; } = new List<INamedTypeSymbol>();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            if (context.Node is ClassDeclarationSyntax declaration && declaration.AttributeLists.Count > 0 &&
                context.SemanticModel.GetDeclaredSymbol(declaration) is INamedTypeSymbol type)
            {
                Types.Add(type);
            }
        }
    }
}
